#!/bin/bash

# Copyright 2018 The Vitess Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# this script creates a dummy my.cnf which won't actually work 
echo "KEYSPACE="$KEYSPACE
echo "SHARD="$SHARD
echo "TABLET_TYPE="$TABLET_TYPE
echo "TABLET_ID="$TABLET_ID
echo "TABLET_DIR="$TABLET_DIR

echo "server-id = 22222"
echo "datadir = /vt/vtdataroot/vt_0000011111/data"
echo "port = 6802"