version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    minimum-version-age: 14
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    minimum-version-age: 14
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
    minimum-version-age: 14
    groups:
      java:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/web/vtadmin"
    schedule:
      interval: "weekly"
    minimum-version-age: 30
    groups:
      vtadmin-npm:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/docker/binaries/*"
      - "/docker/bootstrap"
      - "/docker/lite"
      - "/docker/mini"
      - "/docker/vttestserver"
      - "/examples/compose/external_db/mysql"
      - "/go/mysql/collations/tools/colldump"
    schedule:
      interval: "weekly"
    minimum-version-age: 14
    ignore:
      - dependency-name: "mysql"
        versions:
          - ">= 8.5"
    groups:
      docker:
        patterns:
          - "*"
