# Use the official Go image as a base image
FROM golang:1.24.3

# Set the working directory inside the container
WORKDIR /app

# Copy the go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the working directory inside the container
COPY . .

# Command to run the tests
CMD ["go", "test", "-count=1", "-timeout=60s", "-run", "Metrics", "vitess.io/vitess/go/vt/servenv", "-v"]
