/*
Copyright 2025 The Vitess Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by ASTHelperGen. DO NOT EDIT.

package sqlparser

type ASTStep uint16

const (
	RefOfAddColumnsColumnsOffset ASTStep = iota
	RefOfAddColumnsAfter
	RefOfAddConstraintDefinitionConstraintDefinition
	RefOfAddIndexDefinitionIndexDefinition
	RefOfAliasedExprExpr
	RefOfAliasedExprAs
	RefOfAliasedTableExprExpr
	RefOfAliasedTableExprPartitions
	RefOfAliasedTableExprAs
	RefOfAliasedTableExprHints
	RefOfAliasedTableExprColumns
	RefOfAlterCheckName
	RefOfAlterColumnColumn
	RefOfAlterColumnDefaultVal
	RefOfAlterDatabaseComments
	RefOfAlterDatabaseDBName
	RefOfAlterIndexName
	RefOfAlterMigrationRatio
	RefOfAlterTableTable
	RefOfAlterTableAlterOptionsOffset
	RefOfAlterTablePartitionSpec
	RefOfAlterTablePartitionOption
	RefOfAlterTableComments
	RefOfAlterViewViewName
	RefOfAlterViewDefiner
	RefOfAlterViewColumns
	RefOfAlterViewSelect
	RefOfAlterViewComments
	RefOfAlterVschemaTable
	RefOfAlterVschemaVindexSpec
	RefOfAlterVschemaVindexColsOffset
	RefOfAlterVschemaAutoIncSpec
	RefOfAnalyzeTable
	RefOfAndExprLeft
	RefOfAndExprRight
	RefOfAnyValueArg
	RefOfArgumentLessWindowExprOverClause
	RefOfAssignmentExprLeft
	RefOfAssignmentExprRight
	RefOfAutoIncSpecColumn
	RefOfAutoIncSpecSequence
	RefOfAvgArg
	RefOfAvgOverClause
	RefOfBetweenExprLeft
	RefOfBetweenExprFrom
	RefOfBetweenExprTo
	RefOfBinaryExprLeft
	RefOfBinaryExprRight
	RefOfBitAndArg
	RefOfBitAndOverClause
	RefOfBitOrArg
	RefOfBitOrOverClause
	RefOfBitXorArg
	RefOfBitXorOverClause
	RefOfCallProcName
	RefOfCallProcParamsOffset
	RefOfCaseExprExpr
	RefOfCaseExprWhensOffset
	RefOfCaseExprElse
	RefOfCastExprExpr
	RefOfCastExprType
	RefOfChangeColumnOldColumn
	RefOfChangeColumnNewColDefinition
	RefOfChangeColumnAfter
	RefOfCharExprExprsOffset
	RefOfCheckConstraintDefinitionExpr
	RefOfColNameName
	RefOfColNameQualifier
	RefOfCollateExprExpr
	RefOfColumnDefinitionName
	RefOfColumnDefinitionType
	ColumnsOffset
	RefOfCommonTableExprID
	RefOfCommonTableExprColumns
	RefOfCommonTableExprSubquery
	RefOfComparisonExprLeft
	RefOfComparisonExprRight
	RefOfComparisonExprEscape
	RefOfConstraintDefinitionName
	RefOfConstraintDefinitionDetails
	RefOfConvertExprExpr
	RefOfConvertExprType
	RefOfConvertUsingExprExpr
	RefOfCountArgsOffset
	RefOfCountOverClause
	RefOfCountStarOverClause
	RefOfCreateDatabaseComments
	RefOfCreateDatabaseDBName
	RefOfCreateTableTable
	RefOfCreateTableTableSpec
	RefOfCreateTableOptLike
	RefOfCreateTableComments
	RefOfCreateViewViewName
	RefOfCreateViewDefiner
	RefOfCreateViewColumns
	RefOfCreateViewSelect
	RefOfCreateViewComments
	RefOfCurTimeFuncExprName
	RefOfDeallocateStmtComments
	RefOfDeallocateStmtName
	RefOfDeleteWith
	RefOfDeleteComments
	RefOfDeleteTableExprsOffset
	RefOfDeleteTargets
	RefOfDeletePartitions
	RefOfDeleteWhere
	RefOfDeleteOrderBy
	RefOfDeleteLimit
	RefOfDerivedTableSelect
	RefOfDropColumnName
	RefOfDropDatabaseComments
	RefOfDropDatabaseDBName
	RefOfDropKeyName
	RefOfDropTableFromTables
	RefOfDropTableComments
	RefOfDropViewFromTables
	RefOfDropViewComments
	RefOfExecuteStmtName
	RefOfExecuteStmtComments
	RefOfExecuteStmtArgumentsOffset
	RefOfExistsExprSubquery
	RefOfExplainStmtStatement
	RefOfExplainStmtComments
	RefOfExplainTabTable
	RefOfExprsExprsOffset
	RefOfExtractFuncExprExpr
	RefOfExtractValueExprFragment
	RefOfExtractValueExprXPathExpr
	RefOfFirstOrLastValueExprExpr
	RefOfFirstOrLastValueExprNullTreatmentClause
	RefOfFirstOrLastValueExprOverClause
	RefOfFlushTableNames
	RefOfForeignKeyDefinitionSource
	RefOfForeignKeyDefinitionIndexName
	RefOfForeignKeyDefinitionReferenceDefinition
	RefOfFrameClauseStart
	RefOfFrameClauseEnd
	RefOfFramePointExpr
	RefOfFuncExprQualifier
	RefOfFuncExprName
	RefOfFuncExprExprsOffset
	RefOfGTIDFuncExprSet1
	RefOfGTIDFuncExprSet2
	RefOfGTIDFuncExprTimeout
	RefOfGTIDFuncExprChannel
	RefOfGeoHashFromLatLongExprLatitude
	RefOfGeoHashFromLatLongExprLongitude
	RefOfGeoHashFromLatLongExprMaxLength
	RefOfGeoHashFromPointExprPoint
	RefOfGeoHashFromPointExprMaxLength
	RefOfGeoJSONFromGeomExprGeom
	RefOfGeoJSONFromGeomExprMaxDecimalDigits
	RefOfGeoJSONFromGeomExprBitmask
	RefOfGeomCollPropertyFuncExprGeomColl
	RefOfGeomCollPropertyFuncExprPropertyDefArg
	RefOfGeomFormatExprGeom
	RefOfGeomFormatExprAxisOrderOpt
	RefOfGeomFromGeoHashExprGeoHash
	RefOfGeomFromGeoHashExprSridOpt
	RefOfGeomFromGeoJSONExprGeoJSON
	RefOfGeomFromGeoJSONExprHigherDimHandlerOpt
	RefOfGeomFromGeoJSONExprSrid
	RefOfGeomFromTextExprWktText
	RefOfGeomFromTextExprSrid
	RefOfGeomFromTextExprAxisOrderOpt
	RefOfGeomFromWKBExprWkbBlob
	RefOfGeomFromWKBExprSrid
	RefOfGeomFromWKBExprAxisOrderOpt
	RefOfGeomPropertyFuncExprGeom
	RefOfGroupByExprsOffset
	RefOfGroupConcatExprExprsOffset
	RefOfGroupConcatExprOrderBy
	RefOfGroupConcatExprLimit
	RefOfIndexDefinitionInfo
	RefOfIndexHintIndexesOffset
	IndexHintsOffset
	RefOfIndexInfoName
	RefOfIndexInfoConstraintName
	RefOfInsertComments
	RefOfInsertTable
	RefOfInsertPartitions
	RefOfInsertColumns
	RefOfInsertRows
	RefOfInsertRowAlias
	RefOfInsertOnDup
	RefOfInsertExprStr
	RefOfInsertExprPos
	RefOfInsertExprLen
	RefOfInsertExprNewStr
	RefOfIntervalDateExprDate
	RefOfIntervalDateExprInterval
	RefOfIntervalFuncExprExpr
	RefOfIntervalFuncExprExprsOffset
	RefOfIntroducerExprExpr
	RefOfIsExprLeft
	RefOfJSONArrayAggExpr
	RefOfJSONArrayAggOverClause
	RefOfJSONArrayExprParamsOffset
	RefOfJSONAttributesExprJSONDoc
	RefOfJSONAttributesExprPath
	RefOfJSONContainsExprTarget
	RefOfJSONContainsExprCandidate
	RefOfJSONContainsExprPathListOffset
	RefOfJSONContainsPathExprJSONDoc
	RefOfJSONContainsPathExprOneOrAll
	RefOfJSONContainsPathExprPathListOffset
	RefOfJSONExtractExprJSONDoc
	RefOfJSONExtractExprPathListOffset
	RefOfJSONKeysExprJSONDoc
	RefOfJSONKeysExprPath
	RefOfJSONObjectAggKey
	RefOfJSONObjectAggValue
	RefOfJSONObjectAggOverClause
	RefOfJSONObjectExprParamsOffset
	RefOfJSONObjectParamKey
	RefOfJSONObjectParamValue
	RefOfJSONOverlapsExprJSONDoc1
	RefOfJSONOverlapsExprJSONDoc2
	RefOfJSONPrettyExprJSONVal
	RefOfJSONQuoteExprStringArg
	RefOfJSONRemoveExprJSONDoc
	RefOfJSONRemoveExprPathListOffset
	RefOfJSONSchemaValidFuncExprSchema
	RefOfJSONSchemaValidFuncExprDocument
	RefOfJSONSchemaValidationReportFuncExprSchema
	RefOfJSONSchemaValidationReportFuncExprDocument
	RefOfJSONSearchExprJSONDoc
	RefOfJSONSearchExprOneOrAll
	RefOfJSONSearchExprSearchStr
	RefOfJSONSearchExprEscapeChar
	RefOfJSONSearchExprPathListOffset
	RefOfJSONStorageFreeExprJSONVal
	RefOfJSONStorageSizeExprJSONVal
	RefOfJSONTableExprExpr
	RefOfJSONTableExprAlias
	RefOfJSONTableExprFilter
	RefOfJSONTableExprColumnsOffset
	RefOfJSONUnquoteExprJSONValue
	RefOfJSONValueExprJSONDoc
	RefOfJSONValueExprPath
	RefOfJSONValueExprReturningType
	RefOfJSONValueExprEmptyOnResponse
	RefOfJSONValueExprErrorOnResponse
	RefOfJSONValueMergeExprJSONDoc
	RefOfJSONValueMergeExprJSONDocListOffset
	RefOfJSONValueModifierExprJSONDoc
	RefOfJSONValueModifierExprParamsOffset
	RefOfJoinConditionOn
	RefOfJoinConditionUsing
	RefOfJoinTableExprLeftExpr
	RefOfJoinTableExprRightExpr
	RefOfJoinTableExprCondition
	RefOfJtOnResponseExpr
	RefOfLagLeadExprExpr
	RefOfLagLeadExprN
	RefOfLagLeadExprDefault
	RefOfLagLeadExprOverClause
	RefOfLagLeadExprNullTreatmentClause
	RefOfLimitOffset
	RefOfLimitRowcount
	RefOfLineStringExprPointParamsOffset
	RefOfLinestrPropertyFuncExprLinestring
	RefOfLinestrPropertyFuncExprPropertyDefArg
	RefOfLocateExprSubStr
	RefOfLocateExprStr
	RefOfLocateExprPos
	RefOfLockingFuncName
	RefOfLockingFuncTimeout
	RefOfMatchExprColumnsOffset
	RefOfMatchExprExpr
	RefOfMaxArg
	RefOfMaxOverClause
	RefOfMemberOfExprValue
	RefOfMemberOfExprJSONArr
	RefOfMinArg
	RefOfMinOverClause
	RefOfModifyColumnNewColDefinition
	RefOfModifyColumnAfter
	RefOfMultiLinestringExprLinestringParamsOffset
	RefOfMultiPointExprPointParamsOffset
	RefOfMultiPolygonExprPolygonParamsOffset
	RefOfNTHValueExprExpr
	RefOfNTHValueExprN
	RefOfNTHValueExprOverClause
	RefOfNTHValueExprFromFirstLastClause
	RefOfNTHValueExprNullTreatmentClause
	RefOfNamedWindowWindows
	NamedWindowsOffset
	RefOfNextvalExpr
	RefOfNotExprExpr
	RefOfNtileExprN
	RefOfNtileExprOverClause
	RefOfOffsetOriginal
	OnDupOffset
	RefOfOptLikeLikeTable
	RefOfOrExprLeft
	RefOfOrExprRight
	RefOfOrderExpr
	OrderByOffset
	RefOfOrderByOptionCols
	RefOfOverClauseWindowName
	RefOfOverClauseWindowSpec
	RefOfParenTableExprExprs
	RefOfPartitionDefinitionName
	RefOfPartitionDefinitionOptions
	RefOfPartitionDefinitionOptionsValueRange
	RefOfPartitionDefinitionOptionsComment
	RefOfPartitionDefinitionOptionsEngine
	RefOfPartitionDefinitionOptionsDataDirectory
	RefOfPartitionDefinitionOptionsIndexDirectory
	RefOfPartitionDefinitionOptionsSubPartitionDefinitions
	RefOfPartitionOptionColList
	RefOfPartitionOptionExpr
	RefOfPartitionOptionSubPartition
	RefOfPartitionOptionDefinitionsOffset
	RefOfPartitionSpecNames
	RefOfPartitionSpecNumber
	RefOfPartitionSpecTableName
	RefOfPartitionSpecDefinitionsOffset
	RefOfPartitionValueRangeRange
	PartitionsOffset
	RefOfPerformanceSchemaFuncExprArgument
	RefOfPointExprXCordinate
	RefOfPointExprYCordinate
	RefOfPointPropertyFuncExprPoint
	RefOfPointPropertyFuncExprValueToSet
	RefOfPolygonExprLinestringParamsOffset
	RefOfPolygonPropertyFuncExprPolygon
	RefOfPolygonPropertyFuncExprPropertyDefArg
	RefOfPrepareStmtName
	RefOfPrepareStmtStatement
	RefOfPrepareStmtComments
	RefOfReferenceDefinitionReferencedTable
	RefOfReferenceDefinitionReferencedColumns
	RefOfReferenceDefinitionMatch
	RefOfReferenceDefinitionOnDelete
	RefOfReferenceDefinitionOnUpdate
	RefOfRegexpInstrExprExpr
	RefOfRegexpInstrExprPattern
	RefOfRegexpInstrExprPosition
	RefOfRegexpInstrExprOccurrence
	RefOfRegexpInstrExprReturnOption
	RefOfRegexpInstrExprMatchType
	RefOfRegexpLikeExprExpr
	RefOfRegexpLikeExprPattern
	RefOfRegexpLikeExprMatchType
	RefOfRegexpReplaceExprExpr
	RefOfRegexpReplaceExprPattern
	RefOfRegexpReplaceExprRepl
	RefOfRegexpReplaceExprOccurrence
	RefOfRegexpReplaceExprPosition
	RefOfRegexpReplaceExprMatchType
	RefOfRegexpSubstrExprExpr
	RefOfRegexpSubstrExprPattern
	RefOfRegexpSubstrExprOccurrence
	RefOfRegexpSubstrExprPosition
	RefOfRegexpSubstrExprMatchType
	RefOfReleaseName
	RefOfRenameColumnOldName
	RefOfRenameColumnNewName
	RefOfRenameIndexOldName
	RefOfRenameIndexNewName
	RefOfRenameTableNameTable
	RefOfRevertMigrationComments
	RootNodeSQLNode
	RefOfRowAliasTableName
	RefOfRowAliasColumns
	RefOfSRollbackName
	RefOfSavepointName
	RefOfSelectWith
	RefOfSelectFromOffset
	RefOfSelectComments
	RefOfSelectSelectExprs
	RefOfSelectWhere
	RefOfSelectGroupBy
	RefOfSelectHaving
	RefOfSelectWindows
	RefOfSelectOrderBy
	RefOfSelectLimit
	RefOfSelectInto
	RefOfSelectExprsExprsOffset
	RefOfSetComments
	RefOfSetExprs
	RefOfSetExprVar
	RefOfSetExprExpr
	SetExprsOffset
	RefOfShowInternal
	RefOfShowBasicTbl
	RefOfShowBasicDbName
	RefOfShowBasicFilter
	RefOfShowCreateOp
	RefOfShowFilterFilter
	RefOfShowMigrationLogsComments
	RefOfStarExprTableName
	RefOfStdArg
	RefOfStdOverClause
	RefOfStdDevArg
	RefOfStdDevOverClause
	RefOfStdPopArg
	RefOfStdPopOverClause
	RefOfStdSampArg
	RefOfStdSampOverClause
	RefOfStreamComments
	RefOfStreamSelectExpr
	RefOfStreamTable
	RefOfSubPartitionColList
	RefOfSubPartitionExpr
	RefOfSubPartitionDefinitionName
	RefOfSubPartitionDefinitionOptions
	RefOfSubPartitionDefinitionOptionsComment
	RefOfSubPartitionDefinitionOptionsEngine
	RefOfSubPartitionDefinitionOptionsDataDirectory
	RefOfSubPartitionDefinitionOptionsIndexDirectory
	SubPartitionDefinitionsOffset
	RefOfSubquerySelect
	RefOfSubstrExprName
	RefOfSubstrExprFrom
	RefOfSubstrExprTo
	RefOfSumArg
	RefOfSumOverClause
	TableExprsOffset
	TableNameName
	TableNameQualifier
	TableNamesOffset
	RefOfTableSpecColumnsOffset
	RefOfTableSpecIndexesOffset
	RefOfTableSpecConstraintsOffset
	RefOfTableSpecOptions
	RefOfTableSpecPartitionOption
	RefOfTimestampDiffExprExpr1
	RefOfTimestampDiffExprExpr2
	RefOfTrimFuncExprTrimArg
	RefOfTrimFuncExprStringArg
	RefOfTruncateTableTable
	RefOfUnaryExprExpr
	RefOfUnionWith
	RefOfUnionLeft
	RefOfUnionRight
	RefOfUnionOrderBy
	RefOfUnionLimit
	RefOfUnionInto
	RefOfUpdateWith
	RefOfUpdateComments
	RefOfUpdateTableExprsOffset
	RefOfUpdateExprs
	RefOfUpdateWhere
	RefOfUpdateOrderBy
	RefOfUpdateLimit
	RefOfUpdateExprName
	RefOfUpdateExprExpr
	UpdateExprsOffset
	RefOfUpdateXMLExprTarget
	RefOfUpdateXMLExprXPathExpr
	RefOfUpdateXMLExprNewXML
	RefOfUseDBName
	RefOfVExplainStmtStatement
	RefOfVExplainStmtComments
	RefOfVStreamComments
	RefOfVStreamSelectExpr
	RefOfVStreamTable
	RefOfVStreamWhere
	RefOfVStreamLimit
	ValTupleOffset
	ValuesOffset
	RefOfValuesFuncExprName
	RefOfValuesStatementWith
	RefOfValuesStatementRows
	RefOfValuesStatementListArg
	RefOfValuesStatementComments
	RefOfValuesStatementOrder
	RefOfValuesStatementLimit
	RefOfVarPopArg
	RefOfVarPopOverClause
	RefOfVarSampArg
	RefOfVarSampOverClause
	RefOfVariableName
	RefOfVarianceArg
	RefOfVarianceOverClause
	VindexParamKey
	RefOfVindexSpecName
	RefOfVindexSpecType
	RefOfVindexSpecParamsOffset
	RefOfWeightStringFuncExprExpr
	RefOfWeightStringFuncExprAs
	RefOfWhenCond
	RefOfWhenVal
	RefOfWhereExpr
	RefOfWindowDefinitionName
	RefOfWindowDefinitionWindowSpec
	WindowDefinitionsOffset
	RefOfWindowSpecificationName
	RefOfWindowSpecificationPartitionClauseOffset
	RefOfWindowSpecificationOrderClause
	RefOfWindowSpecificationFrameClause
	RefOfWithCTEsOffset
	RefOfXorExprLeft
	RefOfXorExprRight
	SliceOfRefOfColumnDefinitionOffset
	SliceOfAlterOptionOffset
	SliceOfIdentifierCIOffset
	SliceOfExprOffset
	SliceOfRefOfWhenOffset
	RefOfColumnTypeOptionsDefault
	RefOfColumnTypeOptionsOnUpdate
	RefOfColumnTypeOptionsAs
	RefOfColumnTypeOptionsComment
	RefOfColumnTypeOptionsReference
	RefOfColumnTypeOptionsEngineAttribute
	RefOfColumnTypeOptionsSecondaryEngineAttribute
	RefOfColumnTypeOptionsSRID
	SliceOfTableExprOffset
	SliceOfRefOfVariableOffset
	SliceOfRefOfJSONObjectParamOffset
	SliceOfRefOfJtColumnDefinitionOffset
	RefOfJtOrdinalColDefName
	RefOfJtPathColDefName
	RefOfJtPathColDefType
	RefOfJtPathColDefPath
	RefOfJtPathColDefEmptyOnResponse
	RefOfJtPathColDefErrorOnResponse
	RefOfJtNestedPathColDefPath
	RefOfJtNestedPathColDefColumnsOffset
	SliceOfRefOfColNameOffset
	SliceOfRefOfPartitionDefinitionOffset
	RefOfRootNodeSQLNode
	SliceOfSelectExprOffset
	RefOfTableNameName
	RefOfTableNameQualifier
	RefOfTableOptionValue
	RefOfTableOptionTables
	SliceOfRefOfIndexDefinitionOffset
	SliceOfRefOfConstraintDefinitionOffset
	RefOfVindexParamKey
	SliceOfVindexParamOffset
	SliceOfRefOfCommonTableExprOffset
	RefOfIndexColumnColumn
	RefOfIndexColumnExpression
	RefOfIndexOptionValue
	RefOfTableAndLockTypeTable
	RefOfRenameTablePairFromTable
	RefOfRenameTablePairToTable
)

func (s ASTStep) DebugString() string {
	switch s {
	case RefOfAddColumnsColumnsOffset:
		return "(*AddColumns).ColumnsOffset"
	case RefOfAddColumnsAfter:
		return "(*AddColumns).After"
	case RefOfAddConstraintDefinitionConstraintDefinition:
		return "(*AddConstraintDefinition).ConstraintDefinition"
	case RefOfAddIndexDefinitionIndexDefinition:
		return "(*AddIndexDefinition).IndexDefinition"
	case RefOfAliasedExprExpr:
		return "(*AliasedExpr).Expr"
	case RefOfAliasedExprAs:
		return "(*AliasedExpr).As"
	case RefOfAliasedTableExprExpr:
		return "(*AliasedTableExpr).Expr"
	case RefOfAliasedTableExprPartitions:
		return "(*AliasedTableExpr).Partitions"
	case RefOfAliasedTableExprAs:
		return "(*AliasedTableExpr).As"
	case RefOfAliasedTableExprHints:
		return "(*AliasedTableExpr).Hints"
	case RefOfAliasedTableExprColumns:
		return "(*AliasedTableExpr).Columns"
	case RefOfAlterCheckName:
		return "(*AlterCheck).Name"
	case RefOfAlterColumnColumn:
		return "(*AlterColumn).Column"
	case RefOfAlterColumnDefaultVal:
		return "(*AlterColumn).DefaultVal"
	case RefOfAlterDatabaseComments:
		return "(*AlterDatabase).Comments"
	case RefOfAlterDatabaseDBName:
		return "(*AlterDatabase).DBName"
	case RefOfAlterIndexName:
		return "(*AlterIndex).Name"
	case RefOfAlterMigrationRatio:
		return "(*AlterMigration).Ratio"
	case RefOfAlterTableTable:
		return "(*AlterTable).Table"
	case RefOfAlterTableAlterOptionsOffset:
		return "(*AlterTable).AlterOptionsOffset"
	case RefOfAlterTablePartitionSpec:
		return "(*AlterTable).PartitionSpec"
	case RefOfAlterTablePartitionOption:
		return "(*AlterTable).PartitionOption"
	case RefOfAlterTableComments:
		return "(*AlterTable).Comments"
	case RefOfAlterViewViewName:
		return "(*AlterView).ViewName"
	case RefOfAlterViewDefiner:
		return "(*AlterView).Definer"
	case RefOfAlterViewColumns:
		return "(*AlterView).Columns"
	case RefOfAlterViewSelect:
		return "(*AlterView).Select"
	case RefOfAlterViewComments:
		return "(*AlterView).Comments"
	case RefOfAlterVschemaTable:
		return "(*AlterVschema).Table"
	case RefOfAlterVschemaVindexSpec:
		return "(*AlterVschema).VindexSpec"
	case RefOfAlterVschemaVindexColsOffset:
		return "(*AlterVschema).VindexColsOffset"
	case RefOfAlterVschemaAutoIncSpec:
		return "(*AlterVschema).AutoIncSpec"
	case RefOfAnalyzeTable:
		return "(*Analyze).Table"
	case RefOfAndExprLeft:
		return "(*AndExpr).Left"
	case RefOfAndExprRight:
		return "(*AndExpr).Right"
	case RefOfAnyValueArg:
		return "(*AnyValue).Arg"
	case RefOfArgumentLessWindowExprOverClause:
		return "(*ArgumentLessWindowExpr).OverClause"
	case RefOfAssignmentExprLeft:
		return "(*AssignmentExpr).Left"
	case RefOfAssignmentExprRight:
		return "(*AssignmentExpr).Right"
	case RefOfAutoIncSpecColumn:
		return "(*AutoIncSpec).Column"
	case RefOfAutoIncSpecSequence:
		return "(*AutoIncSpec).Sequence"
	case RefOfAvgArg:
		return "(*Avg).Arg"
	case RefOfAvgOverClause:
		return "(*Avg).OverClause"
	case RefOfBetweenExprLeft:
		return "(*BetweenExpr).Left"
	case RefOfBetweenExprFrom:
		return "(*BetweenExpr).From"
	case RefOfBetweenExprTo:
		return "(*BetweenExpr).To"
	case RefOfBinaryExprLeft:
		return "(*BinaryExpr).Left"
	case RefOfBinaryExprRight:
		return "(*BinaryExpr).Right"
	case RefOfBitAndArg:
		return "(*BitAnd).Arg"
	case RefOfBitAndOverClause:
		return "(*BitAnd).OverClause"
	case RefOfBitOrArg:
		return "(*BitOr).Arg"
	case RefOfBitOrOverClause:
		return "(*BitOr).OverClause"
	case RefOfBitXorArg:
		return "(*BitXor).Arg"
	case RefOfBitXorOverClause:
		return "(*BitXor).OverClause"
	case RefOfCallProcName:
		return "(*CallProc).Name"
	case RefOfCallProcParamsOffset:
		return "(*CallProc).ParamsOffset"
	case RefOfCaseExprExpr:
		return "(*CaseExpr).Expr"
	case RefOfCaseExprWhensOffset:
		return "(*CaseExpr).WhensOffset"
	case RefOfCaseExprElse:
		return "(*CaseExpr).Else"
	case RefOfCastExprExpr:
		return "(*CastExpr).Expr"
	case RefOfCastExprType:
		return "(*CastExpr).Type"
	case RefOfChangeColumnOldColumn:
		return "(*ChangeColumn).OldColumn"
	case RefOfChangeColumnNewColDefinition:
		return "(*ChangeColumn).NewColDefinition"
	case RefOfChangeColumnAfter:
		return "(*ChangeColumn).After"
	case RefOfCharExprExprsOffset:
		return "(*CharExpr).ExprsOffset"
	case RefOfCheckConstraintDefinitionExpr:
		return "(*CheckConstraintDefinition).Expr"
	case RefOfColNameName:
		return "(*ColName).Name"
	case RefOfColNameQualifier:
		return "(*ColName).Qualifier"
	case RefOfCollateExprExpr:
		return "(*CollateExpr).Expr"
	case RefOfColumnDefinitionName:
		return "(*ColumnDefinition).Name"
	case RefOfColumnDefinitionType:
		return "(*ColumnDefinition).Type"
	case ColumnsOffset:
		return "(Columns)[]Offset"
	case RefOfCommonTableExprID:
		return "(*CommonTableExpr).ID"
	case RefOfCommonTableExprColumns:
		return "(*CommonTableExpr).Columns"
	case RefOfCommonTableExprSubquery:
		return "(*CommonTableExpr).Subquery"
	case RefOfComparisonExprLeft:
		return "(*ComparisonExpr).Left"
	case RefOfComparisonExprRight:
		return "(*ComparisonExpr).Right"
	case RefOfComparisonExprEscape:
		return "(*ComparisonExpr).Escape"
	case RefOfConstraintDefinitionName:
		return "(*ConstraintDefinition).Name"
	case RefOfConstraintDefinitionDetails:
		return "(*ConstraintDefinition).Details"
	case RefOfConvertExprExpr:
		return "(*ConvertExpr).Expr"
	case RefOfConvertExprType:
		return "(*ConvertExpr).Type"
	case RefOfConvertUsingExprExpr:
		return "(*ConvertUsingExpr).Expr"
	case RefOfCountArgsOffset:
		return "(*Count).ArgsOffset"
	case RefOfCountOverClause:
		return "(*Count).OverClause"
	case RefOfCountStarOverClause:
		return "(*CountStar).OverClause"
	case RefOfCreateDatabaseComments:
		return "(*CreateDatabase).Comments"
	case RefOfCreateDatabaseDBName:
		return "(*CreateDatabase).DBName"
	case RefOfCreateTableTable:
		return "(*CreateTable).Table"
	case RefOfCreateTableTableSpec:
		return "(*CreateTable).TableSpec"
	case RefOfCreateTableOptLike:
		return "(*CreateTable).OptLike"
	case RefOfCreateTableComments:
		return "(*CreateTable).Comments"
	case RefOfCreateViewViewName:
		return "(*CreateView).ViewName"
	case RefOfCreateViewDefiner:
		return "(*CreateView).Definer"
	case RefOfCreateViewColumns:
		return "(*CreateView).Columns"
	case RefOfCreateViewSelect:
		return "(*CreateView).Select"
	case RefOfCreateViewComments:
		return "(*CreateView).Comments"
	case RefOfCurTimeFuncExprName:
		return "(*CurTimeFuncExpr).Name"
	case RefOfDeallocateStmtComments:
		return "(*DeallocateStmt).Comments"
	case RefOfDeallocateStmtName:
		return "(*DeallocateStmt).Name"
	case RefOfDeleteWith:
		return "(*Delete).With"
	case RefOfDeleteComments:
		return "(*Delete).Comments"
	case RefOfDeleteTableExprsOffset:
		return "(*Delete).TableExprsOffset"
	case RefOfDeleteTargets:
		return "(*Delete).Targets"
	case RefOfDeletePartitions:
		return "(*Delete).Partitions"
	case RefOfDeleteWhere:
		return "(*Delete).Where"
	case RefOfDeleteOrderBy:
		return "(*Delete).OrderBy"
	case RefOfDeleteLimit:
		return "(*Delete).Limit"
	case RefOfDerivedTableSelect:
		return "(*DerivedTable).Select"
	case RefOfDropColumnName:
		return "(*DropColumn).Name"
	case RefOfDropDatabaseComments:
		return "(*DropDatabase).Comments"
	case RefOfDropDatabaseDBName:
		return "(*DropDatabase).DBName"
	case RefOfDropKeyName:
		return "(*DropKey).Name"
	case RefOfDropTableFromTables:
		return "(*DropTable).FromTables"
	case RefOfDropTableComments:
		return "(*DropTable).Comments"
	case RefOfDropViewFromTables:
		return "(*DropView).FromTables"
	case RefOfDropViewComments:
		return "(*DropView).Comments"
	case RefOfExecuteStmtName:
		return "(*ExecuteStmt).Name"
	case RefOfExecuteStmtComments:
		return "(*ExecuteStmt).Comments"
	case RefOfExecuteStmtArgumentsOffset:
		return "(*ExecuteStmt).ArgumentsOffset"
	case RefOfExistsExprSubquery:
		return "(*ExistsExpr).Subquery"
	case RefOfExplainStmtStatement:
		return "(*ExplainStmt).Statement"
	case RefOfExplainStmtComments:
		return "(*ExplainStmt).Comments"
	case RefOfExplainTabTable:
		return "(*ExplainTab).Table"
	case RefOfExprsExprsOffset:
		return "(*Exprs).ExprsOffset"
	case RefOfExtractFuncExprExpr:
		return "(*ExtractFuncExpr).Expr"
	case RefOfExtractValueExprFragment:
		return "(*ExtractValueExpr).Fragment"
	case RefOfExtractValueExprXPathExpr:
		return "(*ExtractValueExpr).XPathExpr"
	case RefOfFirstOrLastValueExprExpr:
		return "(*FirstOrLastValueExpr).Expr"
	case RefOfFirstOrLastValueExprNullTreatmentClause:
		return "(*FirstOrLastValueExpr).NullTreatmentClause"
	case RefOfFirstOrLastValueExprOverClause:
		return "(*FirstOrLastValueExpr).OverClause"
	case RefOfFlushTableNames:
		return "(*Flush).TableNames"
	case RefOfForeignKeyDefinitionSource:
		return "(*ForeignKeyDefinition).Source"
	case RefOfForeignKeyDefinitionIndexName:
		return "(*ForeignKeyDefinition).IndexName"
	case RefOfForeignKeyDefinitionReferenceDefinition:
		return "(*ForeignKeyDefinition).ReferenceDefinition"
	case RefOfFrameClauseStart:
		return "(*FrameClause).Start"
	case RefOfFrameClauseEnd:
		return "(*FrameClause).End"
	case RefOfFramePointExpr:
		return "(*FramePoint).Expr"
	case RefOfFuncExprQualifier:
		return "(*FuncExpr).Qualifier"
	case RefOfFuncExprName:
		return "(*FuncExpr).Name"
	case RefOfFuncExprExprsOffset:
		return "(*FuncExpr).ExprsOffset"
	case RefOfGTIDFuncExprSet1:
		return "(*GTIDFuncExpr).Set1"
	case RefOfGTIDFuncExprSet2:
		return "(*GTIDFuncExpr).Set2"
	case RefOfGTIDFuncExprTimeout:
		return "(*GTIDFuncExpr).Timeout"
	case RefOfGTIDFuncExprChannel:
		return "(*GTIDFuncExpr).Channel"
	case RefOfGeoHashFromLatLongExprLatitude:
		return "(*GeoHashFromLatLongExpr).Latitude"
	case RefOfGeoHashFromLatLongExprLongitude:
		return "(*GeoHashFromLatLongExpr).Longitude"
	case RefOfGeoHashFromLatLongExprMaxLength:
		return "(*GeoHashFromLatLongExpr).MaxLength"
	case RefOfGeoHashFromPointExprPoint:
		return "(*GeoHashFromPointExpr).Point"
	case RefOfGeoHashFromPointExprMaxLength:
		return "(*GeoHashFromPointExpr).MaxLength"
	case RefOfGeoJSONFromGeomExprGeom:
		return "(*GeoJSONFromGeomExpr).Geom"
	case RefOfGeoJSONFromGeomExprMaxDecimalDigits:
		return "(*GeoJSONFromGeomExpr).MaxDecimalDigits"
	case RefOfGeoJSONFromGeomExprBitmask:
		return "(*GeoJSONFromGeomExpr).Bitmask"
	case RefOfGeomCollPropertyFuncExprGeomColl:
		return "(*GeomCollPropertyFuncExpr).GeomColl"
	case RefOfGeomCollPropertyFuncExprPropertyDefArg:
		return "(*GeomCollPropertyFuncExpr).PropertyDefArg"
	case RefOfGeomFormatExprGeom:
		return "(*GeomFormatExpr).Geom"
	case RefOfGeomFormatExprAxisOrderOpt:
		return "(*GeomFormatExpr).AxisOrderOpt"
	case RefOfGeomFromGeoHashExprGeoHash:
		return "(*GeomFromGeoHashExpr).GeoHash"
	case RefOfGeomFromGeoHashExprSridOpt:
		return "(*GeomFromGeoHashExpr).SridOpt"
	case RefOfGeomFromGeoJSONExprGeoJSON:
		return "(*GeomFromGeoJSONExpr).GeoJSON"
	case RefOfGeomFromGeoJSONExprHigherDimHandlerOpt:
		return "(*GeomFromGeoJSONExpr).HigherDimHandlerOpt"
	case RefOfGeomFromGeoJSONExprSrid:
		return "(*GeomFromGeoJSONExpr).Srid"
	case RefOfGeomFromTextExprWktText:
		return "(*GeomFromTextExpr).WktText"
	case RefOfGeomFromTextExprSrid:
		return "(*GeomFromTextExpr).Srid"
	case RefOfGeomFromTextExprAxisOrderOpt:
		return "(*GeomFromTextExpr).AxisOrderOpt"
	case RefOfGeomFromWKBExprWkbBlob:
		return "(*GeomFromWKBExpr).WkbBlob"
	case RefOfGeomFromWKBExprSrid:
		return "(*GeomFromWKBExpr).Srid"
	case RefOfGeomFromWKBExprAxisOrderOpt:
		return "(*GeomFromWKBExpr).AxisOrderOpt"
	case RefOfGeomPropertyFuncExprGeom:
		return "(*GeomPropertyFuncExpr).Geom"
	case RefOfGroupByExprsOffset:
		return "(*GroupBy).ExprsOffset"
	case RefOfGroupConcatExprExprsOffset:
		return "(*GroupConcatExpr).ExprsOffset"
	case RefOfGroupConcatExprOrderBy:
		return "(*GroupConcatExpr).OrderBy"
	case RefOfGroupConcatExprLimit:
		return "(*GroupConcatExpr).Limit"
	case RefOfIndexDefinitionInfo:
		return "(*IndexDefinition).Info"
	case RefOfIndexHintIndexesOffset:
		return "(*IndexHint).IndexesOffset"
	case IndexHintsOffset:
		return "(IndexHints)[]Offset"
	case RefOfIndexInfoName:
		return "(*IndexInfo).Name"
	case RefOfIndexInfoConstraintName:
		return "(*IndexInfo).ConstraintName"
	case RefOfInsertComments:
		return "(*Insert).Comments"
	case RefOfInsertTable:
		return "(*Insert).Table"
	case RefOfInsertPartitions:
		return "(*Insert).Partitions"
	case RefOfInsertColumns:
		return "(*Insert).Columns"
	case RefOfInsertRows:
		return "(*Insert).Rows"
	case RefOfInsertRowAlias:
		return "(*Insert).RowAlias"
	case RefOfInsertOnDup:
		return "(*Insert).OnDup"
	case RefOfInsertExprStr:
		return "(*InsertExpr).Str"
	case RefOfInsertExprPos:
		return "(*InsertExpr).Pos"
	case RefOfInsertExprLen:
		return "(*InsertExpr).Len"
	case RefOfInsertExprNewStr:
		return "(*InsertExpr).NewStr"
	case RefOfIntervalDateExprDate:
		return "(*IntervalDateExpr).Date"
	case RefOfIntervalDateExprInterval:
		return "(*IntervalDateExpr).Interval"
	case RefOfIntervalFuncExprExpr:
		return "(*IntervalFuncExpr).Expr"
	case RefOfIntervalFuncExprExprsOffset:
		return "(*IntervalFuncExpr).ExprsOffset"
	case RefOfIntroducerExprExpr:
		return "(*IntroducerExpr).Expr"
	case RefOfIsExprLeft:
		return "(*IsExpr).Left"
	case RefOfJSONArrayAggExpr:
		return "(*JSONArrayAgg).Expr"
	case RefOfJSONArrayAggOverClause:
		return "(*JSONArrayAgg).OverClause"
	case RefOfJSONArrayExprParamsOffset:
		return "(*JSONArrayExpr).ParamsOffset"
	case RefOfJSONAttributesExprJSONDoc:
		return "(*JSONAttributesExpr).JSONDoc"
	case RefOfJSONAttributesExprPath:
		return "(*JSONAttributesExpr).Path"
	case RefOfJSONContainsExprTarget:
		return "(*JSONContainsExpr).Target"
	case RefOfJSONContainsExprCandidate:
		return "(*JSONContainsExpr).Candidate"
	case RefOfJSONContainsExprPathListOffset:
		return "(*JSONContainsExpr).PathListOffset"
	case RefOfJSONContainsPathExprJSONDoc:
		return "(*JSONContainsPathExpr).JSONDoc"
	case RefOfJSONContainsPathExprOneOrAll:
		return "(*JSONContainsPathExpr).OneOrAll"
	case RefOfJSONContainsPathExprPathListOffset:
		return "(*JSONContainsPathExpr).PathListOffset"
	case RefOfJSONExtractExprJSONDoc:
		return "(*JSONExtractExpr).JSONDoc"
	case RefOfJSONExtractExprPathListOffset:
		return "(*JSONExtractExpr).PathListOffset"
	case RefOfJSONKeysExprJSONDoc:
		return "(*JSONKeysExpr).JSONDoc"
	case RefOfJSONKeysExprPath:
		return "(*JSONKeysExpr).Path"
	case RefOfJSONObjectAggKey:
		return "(*JSONObjectAgg).Key"
	case RefOfJSONObjectAggValue:
		return "(*JSONObjectAgg).Value"
	case RefOfJSONObjectAggOverClause:
		return "(*JSONObjectAgg).OverClause"
	case RefOfJSONObjectExprParamsOffset:
		return "(*JSONObjectExpr).ParamsOffset"
	case RefOfJSONObjectParamKey:
		return "(*JSONObjectParam).Key"
	case RefOfJSONObjectParamValue:
		return "(*JSONObjectParam).Value"
	case RefOfJSONOverlapsExprJSONDoc1:
		return "(*JSONOverlapsExpr).JSONDoc1"
	case RefOfJSONOverlapsExprJSONDoc2:
		return "(*JSONOverlapsExpr).JSONDoc2"
	case RefOfJSONPrettyExprJSONVal:
		return "(*JSONPrettyExpr).JSONVal"
	case RefOfJSONQuoteExprStringArg:
		return "(*JSONQuoteExpr).StringArg"
	case RefOfJSONRemoveExprJSONDoc:
		return "(*JSONRemoveExpr).JSONDoc"
	case RefOfJSONRemoveExprPathListOffset:
		return "(*JSONRemoveExpr).PathListOffset"
	case RefOfJSONSchemaValidFuncExprSchema:
		return "(*JSONSchemaValidFuncExpr).Schema"
	case RefOfJSONSchemaValidFuncExprDocument:
		return "(*JSONSchemaValidFuncExpr).Document"
	case RefOfJSONSchemaValidationReportFuncExprSchema:
		return "(*JSONSchemaValidationReportFuncExpr).Schema"
	case RefOfJSONSchemaValidationReportFuncExprDocument:
		return "(*JSONSchemaValidationReportFuncExpr).Document"
	case RefOfJSONSearchExprJSONDoc:
		return "(*JSONSearchExpr).JSONDoc"
	case RefOfJSONSearchExprOneOrAll:
		return "(*JSONSearchExpr).OneOrAll"
	case RefOfJSONSearchExprSearchStr:
		return "(*JSONSearchExpr).SearchStr"
	case RefOfJSONSearchExprEscapeChar:
		return "(*JSONSearchExpr).EscapeChar"
	case RefOfJSONSearchExprPathListOffset:
		return "(*JSONSearchExpr).PathListOffset"
	case RefOfJSONStorageFreeExprJSONVal:
		return "(*JSONStorageFreeExpr).JSONVal"
	case RefOfJSONStorageSizeExprJSONVal:
		return "(*JSONStorageSizeExpr).JSONVal"
	case RefOfJSONTableExprExpr:
		return "(*JSONTableExpr).Expr"
	case RefOfJSONTableExprAlias:
		return "(*JSONTableExpr).Alias"
	case RefOfJSONTableExprFilter:
		return "(*JSONTableExpr).Filter"
	case RefOfJSONTableExprColumnsOffset:
		return "(*JSONTableExpr).ColumnsOffset"
	case RefOfJSONUnquoteExprJSONValue:
		return "(*JSONUnquoteExpr).JSONValue"
	case RefOfJSONValueExprJSONDoc:
		return "(*JSONValueExpr).JSONDoc"
	case RefOfJSONValueExprPath:
		return "(*JSONValueExpr).Path"
	case RefOfJSONValueExprReturningType:
		return "(*JSONValueExpr).ReturningType"
	case RefOfJSONValueExprEmptyOnResponse:
		return "(*JSONValueExpr).EmptyOnResponse"
	case RefOfJSONValueExprErrorOnResponse:
		return "(*JSONValueExpr).ErrorOnResponse"
	case RefOfJSONValueMergeExprJSONDoc:
		return "(*JSONValueMergeExpr).JSONDoc"
	case RefOfJSONValueMergeExprJSONDocListOffset:
		return "(*JSONValueMergeExpr).JSONDocListOffset"
	case RefOfJSONValueModifierExprJSONDoc:
		return "(*JSONValueModifierExpr).JSONDoc"
	case RefOfJSONValueModifierExprParamsOffset:
		return "(*JSONValueModifierExpr).ParamsOffset"
	case RefOfJoinConditionOn:
		return "(*JoinCondition).On"
	case RefOfJoinConditionUsing:
		return "(*JoinCondition).Using"
	case RefOfJoinTableExprLeftExpr:
		return "(*JoinTableExpr).LeftExpr"
	case RefOfJoinTableExprRightExpr:
		return "(*JoinTableExpr).RightExpr"
	case RefOfJoinTableExprCondition:
		return "(*JoinTableExpr).Condition"
	case RefOfJtOnResponseExpr:
		return "(*JtOnResponse).Expr"
	case RefOfLagLeadExprExpr:
		return "(*LagLeadExpr).Expr"
	case RefOfLagLeadExprN:
		return "(*LagLeadExpr).N"
	case RefOfLagLeadExprDefault:
		return "(*LagLeadExpr).Default"
	case RefOfLagLeadExprOverClause:
		return "(*LagLeadExpr).OverClause"
	case RefOfLagLeadExprNullTreatmentClause:
		return "(*LagLeadExpr).NullTreatmentClause"
	case RefOfLimitOffset:
		return "(*Limit).Offset"
	case RefOfLimitRowcount:
		return "(*Limit).Rowcount"
	case RefOfLineStringExprPointParamsOffset:
		return "(*LineStringExpr).PointParamsOffset"
	case RefOfLinestrPropertyFuncExprLinestring:
		return "(*LinestrPropertyFuncExpr).Linestring"
	case RefOfLinestrPropertyFuncExprPropertyDefArg:
		return "(*LinestrPropertyFuncExpr).PropertyDefArg"
	case RefOfLocateExprSubStr:
		return "(*LocateExpr).SubStr"
	case RefOfLocateExprStr:
		return "(*LocateExpr).Str"
	case RefOfLocateExprPos:
		return "(*LocateExpr).Pos"
	case RefOfLockingFuncName:
		return "(*LockingFunc).Name"
	case RefOfLockingFuncTimeout:
		return "(*LockingFunc).Timeout"
	case RefOfMatchExprColumnsOffset:
		return "(*MatchExpr).ColumnsOffset"
	case RefOfMatchExprExpr:
		return "(*MatchExpr).Expr"
	case RefOfMaxArg:
		return "(*Max).Arg"
	case RefOfMaxOverClause:
		return "(*Max).OverClause"
	case RefOfMemberOfExprValue:
		return "(*MemberOfExpr).Value"
	case RefOfMemberOfExprJSONArr:
		return "(*MemberOfExpr).JSONArr"
	case RefOfMinArg:
		return "(*Min).Arg"
	case RefOfMinOverClause:
		return "(*Min).OverClause"
	case RefOfModifyColumnNewColDefinition:
		return "(*ModifyColumn).NewColDefinition"
	case RefOfModifyColumnAfter:
		return "(*ModifyColumn).After"
	case RefOfMultiLinestringExprLinestringParamsOffset:
		return "(*MultiLinestringExpr).LinestringParamsOffset"
	case RefOfMultiPointExprPointParamsOffset:
		return "(*MultiPointExpr).PointParamsOffset"
	case RefOfMultiPolygonExprPolygonParamsOffset:
		return "(*MultiPolygonExpr).PolygonParamsOffset"
	case RefOfNTHValueExprExpr:
		return "(*NTHValueExpr).Expr"
	case RefOfNTHValueExprN:
		return "(*NTHValueExpr).N"
	case RefOfNTHValueExprOverClause:
		return "(*NTHValueExpr).OverClause"
	case RefOfNTHValueExprFromFirstLastClause:
		return "(*NTHValueExpr).FromFirstLastClause"
	case RefOfNTHValueExprNullTreatmentClause:
		return "(*NTHValueExpr).NullTreatmentClause"
	case RefOfNamedWindowWindows:
		return "(*NamedWindow).Windows"
	case NamedWindowsOffset:
		return "(NamedWindows)[]Offset"
	case RefOfNextvalExpr:
		return "(*Nextval).Expr"
	case RefOfNotExprExpr:
		return "(*NotExpr).Expr"
	case RefOfNtileExprN:
		return "(*NtileExpr).N"
	case RefOfNtileExprOverClause:
		return "(*NtileExpr).OverClause"
	case RefOfOffsetOriginal:
		return "(*Offset).Original"
	case OnDupOffset:
		return "(OnDup)[]Offset"
	case RefOfOptLikeLikeTable:
		return "(*OptLike).LikeTable"
	case RefOfOrExprLeft:
		return "(*OrExpr).Left"
	case RefOfOrExprRight:
		return "(*OrExpr).Right"
	case RefOfOrderExpr:
		return "(*Order).Expr"
	case OrderByOffset:
		return "(OrderBy)[]Offset"
	case RefOfOrderByOptionCols:
		return "(*OrderByOption).Cols"
	case RefOfOverClauseWindowName:
		return "(*OverClause).WindowName"
	case RefOfOverClauseWindowSpec:
		return "(*OverClause).WindowSpec"
	case RefOfParenTableExprExprs:
		return "(*ParenTableExpr).Exprs"
	case RefOfPartitionDefinitionName:
		return "(*PartitionDefinition).Name"
	case RefOfPartitionDefinitionOptions:
		return "(*PartitionDefinition).Options"
	case RefOfPartitionDefinitionOptionsValueRange:
		return "(*PartitionDefinitionOptions).ValueRange"
	case RefOfPartitionDefinitionOptionsComment:
		return "(*PartitionDefinitionOptions).Comment"
	case RefOfPartitionDefinitionOptionsEngine:
		return "(*PartitionDefinitionOptions).Engine"
	case RefOfPartitionDefinitionOptionsDataDirectory:
		return "(*PartitionDefinitionOptions).DataDirectory"
	case RefOfPartitionDefinitionOptionsIndexDirectory:
		return "(*PartitionDefinitionOptions).IndexDirectory"
	case RefOfPartitionDefinitionOptionsSubPartitionDefinitions:
		return "(*PartitionDefinitionOptions).SubPartitionDefinitions"
	case RefOfPartitionOptionColList:
		return "(*PartitionOption).ColList"
	case RefOfPartitionOptionExpr:
		return "(*PartitionOption).Expr"
	case RefOfPartitionOptionSubPartition:
		return "(*PartitionOption).SubPartition"
	case RefOfPartitionOptionDefinitionsOffset:
		return "(*PartitionOption).DefinitionsOffset"
	case RefOfPartitionSpecNames:
		return "(*PartitionSpec).Names"
	case RefOfPartitionSpecNumber:
		return "(*PartitionSpec).Number"
	case RefOfPartitionSpecTableName:
		return "(*PartitionSpec).TableName"
	case RefOfPartitionSpecDefinitionsOffset:
		return "(*PartitionSpec).DefinitionsOffset"
	case RefOfPartitionValueRangeRange:
		return "(*PartitionValueRange).Range"
	case PartitionsOffset:
		return "(Partitions)[]Offset"
	case RefOfPerformanceSchemaFuncExprArgument:
		return "(*PerformanceSchemaFuncExpr).Argument"
	case RefOfPointExprXCordinate:
		return "(*PointExpr).XCordinate"
	case RefOfPointExprYCordinate:
		return "(*PointExpr).YCordinate"
	case RefOfPointPropertyFuncExprPoint:
		return "(*PointPropertyFuncExpr).Point"
	case RefOfPointPropertyFuncExprValueToSet:
		return "(*PointPropertyFuncExpr).ValueToSet"
	case RefOfPolygonExprLinestringParamsOffset:
		return "(*PolygonExpr).LinestringParamsOffset"
	case RefOfPolygonPropertyFuncExprPolygon:
		return "(*PolygonPropertyFuncExpr).Polygon"
	case RefOfPolygonPropertyFuncExprPropertyDefArg:
		return "(*PolygonPropertyFuncExpr).PropertyDefArg"
	case RefOfPrepareStmtName:
		return "(*PrepareStmt).Name"
	case RefOfPrepareStmtStatement:
		return "(*PrepareStmt).Statement"
	case RefOfPrepareStmtComments:
		return "(*PrepareStmt).Comments"
	case RefOfReferenceDefinitionReferencedTable:
		return "(*ReferenceDefinition).ReferencedTable"
	case RefOfReferenceDefinitionReferencedColumns:
		return "(*ReferenceDefinition).ReferencedColumns"
	case RefOfReferenceDefinitionMatch:
		return "(*ReferenceDefinition).Match"
	case RefOfReferenceDefinitionOnDelete:
		return "(*ReferenceDefinition).OnDelete"
	case RefOfReferenceDefinitionOnUpdate:
		return "(*ReferenceDefinition).OnUpdate"
	case RefOfRegexpInstrExprExpr:
		return "(*RegexpInstrExpr).Expr"
	case RefOfRegexpInstrExprPattern:
		return "(*RegexpInstrExpr).Pattern"
	case RefOfRegexpInstrExprPosition:
		return "(*RegexpInstrExpr).Position"
	case RefOfRegexpInstrExprOccurrence:
		return "(*RegexpInstrExpr).Occurrence"
	case RefOfRegexpInstrExprReturnOption:
		return "(*RegexpInstrExpr).ReturnOption"
	case RefOfRegexpInstrExprMatchType:
		return "(*RegexpInstrExpr).MatchType"
	case RefOfRegexpLikeExprExpr:
		return "(*RegexpLikeExpr).Expr"
	case RefOfRegexpLikeExprPattern:
		return "(*RegexpLikeExpr).Pattern"
	case RefOfRegexpLikeExprMatchType:
		return "(*RegexpLikeExpr).MatchType"
	case RefOfRegexpReplaceExprExpr:
		return "(*RegexpReplaceExpr).Expr"
	case RefOfRegexpReplaceExprPattern:
		return "(*RegexpReplaceExpr).Pattern"
	case RefOfRegexpReplaceExprRepl:
		return "(*RegexpReplaceExpr).Repl"
	case RefOfRegexpReplaceExprOccurrence:
		return "(*RegexpReplaceExpr).Occurrence"
	case RefOfRegexpReplaceExprPosition:
		return "(*RegexpReplaceExpr).Position"
	case RefOfRegexpReplaceExprMatchType:
		return "(*RegexpReplaceExpr).MatchType"
	case RefOfRegexpSubstrExprExpr:
		return "(*RegexpSubstrExpr).Expr"
	case RefOfRegexpSubstrExprPattern:
		return "(*RegexpSubstrExpr).Pattern"
	case RefOfRegexpSubstrExprOccurrence:
		return "(*RegexpSubstrExpr).Occurrence"
	case RefOfRegexpSubstrExprPosition:
		return "(*RegexpSubstrExpr).Position"
	case RefOfRegexpSubstrExprMatchType:
		return "(*RegexpSubstrExpr).MatchType"
	case RefOfReleaseName:
		return "(*Release).Name"
	case RefOfRenameColumnOldName:
		return "(*RenameColumn).OldName"
	case RefOfRenameColumnNewName:
		return "(*RenameColumn).NewName"
	case RefOfRenameIndexOldName:
		return "(*RenameIndex).OldName"
	case RefOfRenameIndexNewName:
		return "(*RenameIndex).NewName"
	case RefOfRenameTableNameTable:
		return "(*RenameTableName).Table"
	case RefOfRevertMigrationComments:
		return "(*RevertMigration).Comments"
	case RootNodeSQLNode:
		return "(RootNode).SQLNode"
	case RefOfRowAliasTableName:
		return "(*RowAlias).TableName"
	case RefOfRowAliasColumns:
		return "(*RowAlias).Columns"
	case RefOfSRollbackName:
		return "(*SRollback).Name"
	case RefOfSavepointName:
		return "(*Savepoint).Name"
	case RefOfSelectWith:
		return "(*Select).With"
	case RefOfSelectFromOffset:
		return "(*Select).FromOffset"
	case RefOfSelectComments:
		return "(*Select).Comments"
	case RefOfSelectSelectExprs:
		return "(*Select).SelectExprs"
	case RefOfSelectWhere:
		return "(*Select).Where"
	case RefOfSelectGroupBy:
		return "(*Select).GroupBy"
	case RefOfSelectHaving:
		return "(*Select).Having"
	case RefOfSelectWindows:
		return "(*Select).Windows"
	case RefOfSelectOrderBy:
		return "(*Select).OrderBy"
	case RefOfSelectLimit:
		return "(*Select).Limit"
	case RefOfSelectInto:
		return "(*Select).Into"
	case RefOfSelectExprsExprsOffset:
		return "(*SelectExprs).ExprsOffset"
	case RefOfSetComments:
		return "(*Set).Comments"
	case RefOfSetExprs:
		return "(*Set).Exprs"
	case RefOfSetExprVar:
		return "(*SetExpr).Var"
	case RefOfSetExprExpr:
		return "(*SetExpr).Expr"
	case SetExprsOffset:
		return "(SetExprs)[]Offset"
	case RefOfShowInternal:
		return "(*Show).Internal"
	case RefOfShowBasicTbl:
		return "(*ShowBasic).Tbl"
	case RefOfShowBasicDbName:
		return "(*ShowBasic).DbName"
	case RefOfShowBasicFilter:
		return "(*ShowBasic).Filter"
	case RefOfShowCreateOp:
		return "(*ShowCreate).Op"
	case RefOfShowFilterFilter:
		return "(*ShowFilter).Filter"
	case RefOfShowMigrationLogsComments:
		return "(*ShowMigrationLogs).Comments"
	case RefOfStarExprTableName:
		return "(*StarExpr).TableName"
	case RefOfStdArg:
		return "(*Std).Arg"
	case RefOfStdOverClause:
		return "(*Std).OverClause"
	case RefOfStdDevArg:
		return "(*StdDev).Arg"
	case RefOfStdDevOverClause:
		return "(*StdDev).OverClause"
	case RefOfStdPopArg:
		return "(*StdPop).Arg"
	case RefOfStdPopOverClause:
		return "(*StdPop).OverClause"
	case RefOfStdSampArg:
		return "(*StdSamp).Arg"
	case RefOfStdSampOverClause:
		return "(*StdSamp).OverClause"
	case RefOfStreamComments:
		return "(*Stream).Comments"
	case RefOfStreamSelectExpr:
		return "(*Stream).SelectExpr"
	case RefOfStreamTable:
		return "(*Stream).Table"
	case RefOfSubPartitionColList:
		return "(*SubPartition).ColList"
	case RefOfSubPartitionExpr:
		return "(*SubPartition).Expr"
	case RefOfSubPartitionDefinitionName:
		return "(*SubPartitionDefinition).Name"
	case RefOfSubPartitionDefinitionOptions:
		return "(*SubPartitionDefinition).Options"
	case RefOfSubPartitionDefinitionOptionsComment:
		return "(*SubPartitionDefinitionOptions).Comment"
	case RefOfSubPartitionDefinitionOptionsEngine:
		return "(*SubPartitionDefinitionOptions).Engine"
	case RefOfSubPartitionDefinitionOptionsDataDirectory:
		return "(*SubPartitionDefinitionOptions).DataDirectory"
	case RefOfSubPartitionDefinitionOptionsIndexDirectory:
		return "(*SubPartitionDefinitionOptions).IndexDirectory"
	case SubPartitionDefinitionsOffset:
		return "(SubPartitionDefinitions)[]Offset"
	case RefOfSubquerySelect:
		return "(*Subquery).Select"
	case RefOfSubstrExprName:
		return "(*SubstrExpr).Name"
	case RefOfSubstrExprFrom:
		return "(*SubstrExpr).From"
	case RefOfSubstrExprTo:
		return "(*SubstrExpr).To"
	case RefOfSumArg:
		return "(*Sum).Arg"
	case RefOfSumOverClause:
		return "(*Sum).OverClause"
	case TableExprsOffset:
		return "(TableExprs)[]Offset"
	case TableNameName:
		return "(TableName).Name"
	case TableNameQualifier:
		return "(TableName).Qualifier"
	case TableNamesOffset:
		return "(TableNames)[]Offset"
	case RefOfTableSpecColumnsOffset:
		return "(*TableSpec).ColumnsOffset"
	case RefOfTableSpecIndexesOffset:
		return "(*TableSpec).IndexesOffset"
	case RefOfTableSpecConstraintsOffset:
		return "(*TableSpec).ConstraintsOffset"
	case RefOfTableSpecOptions:
		return "(*TableSpec).Options"
	case RefOfTableSpecPartitionOption:
		return "(*TableSpec).PartitionOption"
	case RefOfTimestampDiffExprExpr1:
		return "(*TimestampDiffExpr).Expr1"
	case RefOfTimestampDiffExprExpr2:
		return "(*TimestampDiffExpr).Expr2"
	case RefOfTrimFuncExprTrimArg:
		return "(*TrimFuncExpr).TrimArg"
	case RefOfTrimFuncExprStringArg:
		return "(*TrimFuncExpr).StringArg"
	case RefOfTruncateTableTable:
		return "(*TruncateTable).Table"
	case RefOfUnaryExprExpr:
		return "(*UnaryExpr).Expr"
	case RefOfUnionWith:
		return "(*Union).With"
	case RefOfUnionLeft:
		return "(*Union).Left"
	case RefOfUnionRight:
		return "(*Union).Right"
	case RefOfUnionOrderBy:
		return "(*Union).OrderBy"
	case RefOfUnionLimit:
		return "(*Union).Limit"
	case RefOfUnionInto:
		return "(*Union).Into"
	case RefOfUpdateWith:
		return "(*Update).With"
	case RefOfUpdateComments:
		return "(*Update).Comments"
	case RefOfUpdateTableExprsOffset:
		return "(*Update).TableExprsOffset"
	case RefOfUpdateExprs:
		return "(*Update).Exprs"
	case RefOfUpdateWhere:
		return "(*Update).Where"
	case RefOfUpdateOrderBy:
		return "(*Update).OrderBy"
	case RefOfUpdateLimit:
		return "(*Update).Limit"
	case RefOfUpdateExprName:
		return "(*UpdateExpr).Name"
	case RefOfUpdateExprExpr:
		return "(*UpdateExpr).Expr"
	case UpdateExprsOffset:
		return "(UpdateExprs)[]Offset"
	case RefOfUpdateXMLExprTarget:
		return "(*UpdateXMLExpr).Target"
	case RefOfUpdateXMLExprXPathExpr:
		return "(*UpdateXMLExpr).XPathExpr"
	case RefOfUpdateXMLExprNewXML:
		return "(*UpdateXMLExpr).NewXML"
	case RefOfUseDBName:
		return "(*Use).DBName"
	case RefOfVExplainStmtStatement:
		return "(*VExplainStmt).Statement"
	case RefOfVExplainStmtComments:
		return "(*VExplainStmt).Comments"
	case RefOfVStreamComments:
		return "(*VStream).Comments"
	case RefOfVStreamSelectExpr:
		return "(*VStream).SelectExpr"
	case RefOfVStreamTable:
		return "(*VStream).Table"
	case RefOfVStreamWhere:
		return "(*VStream).Where"
	case RefOfVStreamLimit:
		return "(*VStream).Limit"
	case ValTupleOffset:
		return "(ValTuple)[]Offset"
	case ValuesOffset:
		return "(Values)[]Offset"
	case RefOfValuesFuncExprName:
		return "(*ValuesFuncExpr).Name"
	case RefOfValuesStatementWith:
		return "(*ValuesStatement).With"
	case RefOfValuesStatementRows:
		return "(*ValuesStatement).Rows"
	case RefOfValuesStatementListArg:
		return "(*ValuesStatement).ListArg"
	case RefOfValuesStatementComments:
		return "(*ValuesStatement).Comments"
	case RefOfValuesStatementOrder:
		return "(*ValuesStatement).Order"
	case RefOfValuesStatementLimit:
		return "(*ValuesStatement).Limit"
	case RefOfVarPopArg:
		return "(*VarPop).Arg"
	case RefOfVarPopOverClause:
		return "(*VarPop).OverClause"
	case RefOfVarSampArg:
		return "(*VarSamp).Arg"
	case RefOfVarSampOverClause:
		return "(*VarSamp).OverClause"
	case RefOfVariableName:
		return "(*Variable).Name"
	case RefOfVarianceArg:
		return "(*Variance).Arg"
	case RefOfVarianceOverClause:
		return "(*Variance).OverClause"
	case VindexParamKey:
		return "(VindexParam).Key"
	case RefOfVindexSpecName:
		return "(*VindexSpec).Name"
	case RefOfVindexSpecType:
		return "(*VindexSpec).Type"
	case RefOfVindexSpecParamsOffset:
		return "(*VindexSpec).ParamsOffset"
	case RefOfWeightStringFuncExprExpr:
		return "(*WeightStringFuncExpr).Expr"
	case RefOfWeightStringFuncExprAs:
		return "(*WeightStringFuncExpr).As"
	case RefOfWhenCond:
		return "(*When).Cond"
	case RefOfWhenVal:
		return "(*When).Val"
	case RefOfWhereExpr:
		return "(*Where).Expr"
	case RefOfWindowDefinitionName:
		return "(*WindowDefinition).Name"
	case RefOfWindowDefinitionWindowSpec:
		return "(*WindowDefinition).WindowSpec"
	case WindowDefinitionsOffset:
		return "(WindowDefinitions)[]Offset"
	case RefOfWindowSpecificationName:
		return "(*WindowSpecification).Name"
	case RefOfWindowSpecificationPartitionClauseOffset:
		return "(*WindowSpecification).PartitionClauseOffset"
	case RefOfWindowSpecificationOrderClause:
		return "(*WindowSpecification).OrderClause"
	case RefOfWindowSpecificationFrameClause:
		return "(*WindowSpecification).FrameClause"
	case RefOfWithCTEsOffset:
		return "(*With).CTEsOffset"
	case RefOfXorExprLeft:
		return "(*XorExpr).Left"
	case RefOfXorExprRight:
		return "(*XorExpr).Right"
	case SliceOfRefOfColumnDefinitionOffset:
		return "([]*ColumnDefinition)[]Offset"
	case SliceOfAlterOptionOffset:
		return "([]AlterOption)[]Offset"
	case SliceOfIdentifierCIOffset:
		return "([]IdentifierCI)[]Offset"
	case SliceOfExprOffset:
		return "([]Expr)[]Offset"
	case SliceOfRefOfWhenOffset:
		return "([]*When)[]Offset"
	case RefOfColumnTypeOptionsDefault:
		return "(*ColumnTypeOptions).Default"
	case RefOfColumnTypeOptionsOnUpdate:
		return "(*ColumnTypeOptions).OnUpdate"
	case RefOfColumnTypeOptionsAs:
		return "(*ColumnTypeOptions).As"
	case RefOfColumnTypeOptionsComment:
		return "(*ColumnTypeOptions).Comment"
	case RefOfColumnTypeOptionsReference:
		return "(*ColumnTypeOptions).Reference"
	case RefOfColumnTypeOptionsEngineAttribute:
		return "(*ColumnTypeOptions).EngineAttribute"
	case RefOfColumnTypeOptionsSecondaryEngineAttribute:
		return "(*ColumnTypeOptions).SecondaryEngineAttribute"
	case RefOfColumnTypeOptionsSRID:
		return "(*ColumnTypeOptions).SRID"
	case SliceOfTableExprOffset:
		return "([]TableExpr)[]Offset"
	case SliceOfRefOfVariableOffset:
		return "([]*Variable)[]Offset"
	case SliceOfRefOfJSONObjectParamOffset:
		return "([]*JSONObjectParam)[]Offset"
	case SliceOfRefOfJtColumnDefinitionOffset:
		return "([]*JtColumnDefinition)[]Offset"
	case RefOfJtOrdinalColDefName:
		return "(*JtOrdinalColDef).Name"
	case RefOfJtPathColDefName:
		return "(*JtPathColDef).Name"
	case RefOfJtPathColDefType:
		return "(*JtPathColDef).Type"
	case RefOfJtPathColDefPath:
		return "(*JtPathColDef).Path"
	case RefOfJtPathColDefEmptyOnResponse:
		return "(*JtPathColDef).EmptyOnResponse"
	case RefOfJtPathColDefErrorOnResponse:
		return "(*JtPathColDef).ErrorOnResponse"
	case RefOfJtNestedPathColDefPath:
		return "(*JtNestedPathColDef).Path"
	case RefOfJtNestedPathColDefColumnsOffset:
		return "(*JtNestedPathColDef).ColumnsOffset"
	case SliceOfRefOfColNameOffset:
		return "([]*ColName)[]Offset"
	case SliceOfRefOfPartitionDefinitionOffset:
		return "([]*PartitionDefinition)[]Offset"
	case RefOfRootNodeSQLNode:
		return "(*RootNode).SQLNode"
	case SliceOfSelectExprOffset:
		return "([]SelectExpr)[]Offset"
	case RefOfTableNameName:
		return "(*TableName).Name"
	case RefOfTableNameQualifier:
		return "(*TableName).Qualifier"
	case RefOfTableOptionValue:
		return "(*TableOption).Value"
	case RefOfTableOptionTables:
		return "(*TableOption).Tables"
	case SliceOfRefOfIndexDefinitionOffset:
		return "([]*IndexDefinition)[]Offset"
	case SliceOfRefOfConstraintDefinitionOffset:
		return "([]*ConstraintDefinition)[]Offset"
	case RefOfVindexParamKey:
		return "(*VindexParam).Key"
	case SliceOfVindexParamOffset:
		return "([]VindexParam)[]Offset"
	case SliceOfRefOfCommonTableExprOffset:
		return "([]*CommonTableExpr)[]Offset"
	case RefOfIndexColumnColumn:
		return "(*IndexColumn).Column"
	case RefOfIndexColumnExpression:
		return "(*IndexColumn).Expression"
	case RefOfIndexOptionValue:
		return "(*IndexOption).Value"
	case RefOfTableAndLockTypeTable:
		return "(*TableAndLockType).Table"
	case RefOfRenameTablePairFromTable:
		return "(*RenameTablePair).FromTable"
	case RefOfRenameTablePairToTable:
		return "(*RenameTablePair).ToTable"
	}
	panic("unknown ASTStep")
}
