# Copyright 2026 The Vitess Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG bootstrap_version
ARG image="vitess/bootstrap:${bootstrap_version}-common"

FROM $image

USER root

# Install Percona 8.0
RUN for i in $(seq 1 10); do apt-key adv --no-tty --keyserver keyserver.ubuntu.com --recv-keys 9334A25F8507EFA5 && break; done \
    && echo 'deb http://repo.percona.com/ps-80/apt bookworm main' > /etc/apt/sources.list.d/percona.list && \
    { \
        echo debconf debconf/frontend select Noninteractive; \
        echo percona-server-server-8.0 percona-server-server/root_password password 'unused'; \
        echo percona-server-server-8.0 percona-server-server/root_password_again password 'unused'; \
    } | debconf-set-selections \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        percona-server-server \
	libperconaserverclient21 \
	percona-server-rocksdb \
	bzip2 \
	libdbd-mysql-perl \
	rsync \
	libev4 \
#    && rm -f /etc/apt/sources.list.d/percona.list \
    && echo 'deb http://repo.percona.com/apt bookworm main' > /etc/apt/sources.list.d/percona.list \
#    { \
#        echo debconf debconf/frontend select Noninteractive; \
#        echo percona-server-server-8.0 percona-server-server/root_password password 'unused'; \
#        echo percona-server-server-8.0 percona-server-server/root_password_again password 'unused'; \
#    } | debconf-set-selections \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends percona-xtrabackup-80 \
    && rm -rf /var/lib/apt/lists/* \
    # Remove percona-telemetry-agent binary (CVE-2025-22871 in net/http)
    && rm -f /usr/bin/percona-telemetry-agent

USER vitess
