#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '^go/.*\.go$')

[ -z "$gofiles" ] && exit 0
unformatted=$(gofmt -s -l $gofiles 2>&1)
[ -z "$unformatted" ] && exit 0

# Some files are not gofmt'd. Print message and fail.

echo >&2 "Go files must be formatted with gofmt. Please run:"
echo >&2
echo -n >&2 "  gofmt -s -w"
for fn in $unformatted; do
    echo -n >&2 " $PWD/$fn"
done
echo

exit 1
