#!/bin/bash
# Copyright 2019 The Vitess Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Required version of golangci-lint
REQUIRED_VERSION="v1.60.1"

# Check if golangci-lint is installed and capture the version
if ! command -v golangci-lint >/dev/null 2>&1; then
  echo "golangci-lint not found. Installing version $REQUIRED_VERSION..."
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@$REQUIRED_VERSION
else
  VERSION_OUTPUT=$(golangci-lint --version)
  INSTALLED_VERSION=$(echo "$VERSION_OUTPUT" | sed -n 's/^golangci-lint has version \([v0-9.]*\).*/\1/p')
  if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
    echo "golangci-lint version $INSTALLED_VERSION found, but $REQUIRED_VERSION is required."
    echo "Installing correct version $REQUIRED_VERSION..."
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@$REQUIRED_VERSION
  fi
fi

# Get list of Go files to lint
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '^go/.*\.go$')
if [ -z "$gofiles" ]; then
  exit 0
fi

# Get unique directories of the Go files
gopackages=$(echo "$gofiles" | xargs -n1 dirname | sort -u | paste -sd ' ' -)

# Lint the Go packages
echo "Linting $gopackages"
golangci-lint run $gopackages