#!/bin/bash
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git golint pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

if [ -z "$(which golint)" ]; then
  echo "golint not found, please run: go get github.com/golang/lint/golint"
  exit 1
fi

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '^go/.*\.go$')

errors=

# Run on one file at a time because a single invocation of golint 
# with multiple files requires the files to all be in one package.
for gofile in $gofiles
do
  errcount=$(golint $gofile | wc -l)
  if [ "$errcount" -gt "0" ]; then
    errors=YES
    echo "$errcount suggestions for: golint $gofile"
  fi
done

[ -z "$errors" ] && exit 0

# git doesn't give us access to user input, so let's steal it.
exec < /dev/tty

echo
echo "Lint suggestions were found. They're not enforced, but we're pausing"
echo "to let you know before they get clobbered in the scrollback buffer."
echo
read -r -p 'Press enter to cancel, or type "ack" to continue: '
if [ "$REPLY" != "ack" ]; then
  exit 1
fi
