#!/bin/bash
# Copyright 2019 The Vitess Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# this script, which should run before committing code, makes sure that the visitor is re-generated when the ast changes

make visitor REWRITER=tmp_rewriter.go
if ! cmp -s "tmp_rewriter.go" "go/vt/sqlparser/rewriter.go"; then
	echo "The ast.go has changed, but not rewriter.go"
	echo "You should 'make visitor' to update the generated rewriter"
	rm -f tmp_rewriter.go
	exit 1
fi
rm -f tmp_rewriter.go