FROM scratch

COPY docker-compose.yaml /docker-compose.yaml
COPY .env /.env

# Shell scripts
COPY run-forever.sh /run-forever.sh
COPY schemaload.sh /schemaload.sh
COPY vttablet-up.sh /vttablet-up.sh
COPY vtorc-up.sh /vtorc-up.sh
COPY set_keyspace_durability_policy.sh /set_keyspace_durability_policy.sh
COPY source_db_vreplication.sh /source_db_vreplication.sh
COPY init_cell.sh /init_cell.sh

# VSchema JSON files
COPY default_vschema.json /default_vschema.json
COPY test_keyspace_vschema.json /test_keyspace_vschema.json
COPY lookup_keyspace_vschema.json /lookup_keyspace_vschema.json

# Schema SQL files
COPY tables/test_keyspace_schema_file.sql /tables/test_keyspace_schema_file.sql
COPY tables/lookup_keyspace_schema_file.sql /tables/lookup_keyspace_schema_file.sql

# VTTablet config
COPY config/init_db.sql /config/init_db.sql

# VTOrc config
COPY vtorc/default.json /vtorc/default.json