FROM scratch

COPY docker-compose.yaml /docker-compose.yaml

# This compose file contains Antithesis-specific overrides/extensions.
COPY docker-compose.antithesis.yml /docker-compose.antithesis.yml
COPY .env /.env
