# Copyright 2025 The Vitess Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stage 1: Build all Vitess Go binaries (uninstrumented)
FROM golang:1.26.2-trixie@sha256:4a7137ea573f79c86ae451ff05817ed762ef5597fcf732259e97abeb3108d873 AS go-builder

# Allows docker builds to set the BUILD_NUMBER
ARG BUILD_NUMBER

# Allows docker builds to set the BUILD_GIT_BRANCH
ARG BUILD_GIT_BRANCH

# Allows docker builds to set the BUILD_GIT_REV
ARG BUILD_GIT_REV

# Allows docker builds to set the BUILD_TIME
ARG BUILD_TIME

WORKDIR /vt/src/vitess.io/vitess

# Create vitess user
RUN groupadd -r vitess && useradd -r -g vitess vitess
RUN mkdir -p /vt/vtdataroot /home/vitess
RUN chown -R vitess:vitess /vt /home/vitess
USER vitess

# Copy go.mod/go.sum and install dependencies separately.
COPY --chown=vitess:vitess go.mod go.sum /vt/src/vitess.io/vitess/
RUN go mod download

# Copy the rest of the source and build the binaries.
COPY --chown=vitess:vitess . /vt/src/vitess.io/vitess
RUN make install PREFIX=/vt/install NOVTADMINBUILD=1

# Build vtadmin separately.
FROM node:25-trixie-slim@sha256:04190ed2dee64158e96dd16bc6073fe6502eb3bc14be680b3e7463d048c797eb AS vtadmin-builder

WORKDIR /vt/web/vtadmin

# Copy package.json/package-lock.json and install dependencies separately.
COPY web/vtadmin/package.json web/vtadmin/package-lock.json /vt/web/vtadmin/
RUN npm ci

# Copy the rest of the source and build the static files.
COPY web/vtadmin/ /vt/web/vtadmin/
RUN VITE_VTADMIN_API_ADDRESS="http://localhost:14200" \
    VITE_ENABLE_EXPERIMENTAL_TABLET_DEBUG_VARS="true" \
    npm run build

# Stage 2: Instrument source and rebuild target binaries
FROM go-builder AS instrumentor

RUN mkdir -p /vt/instrumented && \
    go tool antithesis-go-instrumentor \
      -exclude /vt/src/vitess.io/vitess/test/antithesis/instrumentor-exclude.txt \
      /vt/src/vitess.io/vitess /vt/instrumented
WORKDIR /vt/instrumented/customer
RUN go mod tidy
# Antithesis recommends compiling with race detection
RUN CGO_ENABLED=1 go build -race -o /vt/install/bin/vtorc ./go/cmd/vtorc
# The theory is that by exploring interesting behaviors in vttablet and vtctld we will trigger interesting
# behaviors in vtorc. 
RUN CGO_ENABLED=1 go build -race -o /vt/install/bin/vttablet ./go/cmd/vttablet
RUN CGO_ENABLED=1 go build -race -o /vt/install/bin/vtctld ./go/cmd/vtctld

# Stage 3: Final image
FROM debian:trixie-slim@sha256:26f98ccd92fd0a44d6928ce8ff8f4921b4d2f535bfa07555ee5d18f61429cf0c

# Install locale required for mysqlsh
RUN apt-get update && apt-get install -y locales tar \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen en_US.UTF-8

# Install dependencies
COPY docker/utils/install_dependencies.sh /vt/dist/install_dependencies.sh
RUN /vt/dist/install_dependencies.sh mysql84

# Set up Vitess user and directory tree.
RUN groupadd -r vitess && useradd -r -g vitess vitess
RUN mkdir -p /vt/vtdataroot /home/vitess && chown -R vitess:vitess /vt /home/vitess

# Set up Vitess environment (just enough to run pre-built Go binaries)
ENV VTROOT=/vt
ENV VTDATAROOT=/vt/vtdataroot
ENV PATH=$VTROOT/bin:$PATH

# Copy artifacts from builder layers.
COPY --from=go-builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=instrumentor --chown=vitess:vitess /vt/install /vt
COPY --from=go-builder --chown=vitess:vitess /vt/src/vitess.io/vitess/web/vtadmin /vt/web/vtadmin
COPY --from=vtadmin-builder --chown=vitess:vitess /vt/web/vtadmin/build /vt/web/vtadmin/build
COPY --from=instrumentor --chown=vitess:vitess /vt/instrumented/symbols /symbols/
COPY --from=go-builder --chown=vitess:vitess /vt/src/vitess.io/vitess/config/init_db.sql /vt/config/
COPY --from=go-builder --chown=vitess:vitess /vt/src/vitess.io/vitess/config/mycnf /vt/config/

# Create mount point for actual data (e.g. MySQL data dir)
VOLUME /vt/vtdataroot
USER vitess
