package vreplication

var dryRunResultsSwitchWritesCustomerShard = []string{
	"Lock keyspace product",
	"Lock keyspace customer",
	"Stop writes on keyspace product, tables customer:",
	"/       Keyspace product, Shard 0 at Position.*",
	"Wait for VReplication on stopped streams to catchup for upto 30s",
	"Create reverse replication workflow p2c_reverse",
	"Create journal entries on source databases",
	"Enable writes on keyspace customer tables customer",
	"Switch routing from keyspace product to keyspace customer",
	"Following rules will be deleted:",
	"       customer.customer@rdonly => customer.customer",
	"       customer.customer@replica => customer.customer",
	"       customer@rdonly => customer.customer",
	"       customer@replica => customer.customer",
	"       product.customer@rdonly => customer.customer",
	"       product.customer@replica => customer.customer",
	"Following rules will be added:",
	"       customer => customer.customer",
	"       product.customer => customer.customer",
	"SwitchWrites completed, freeze and delete vreplication streams on:",
	"       tablet cell:\"zone1\" uid:200 ",
	"       tablet cell:\"zone1\" uid:300 ",
	"Start reverse replication streams on:",
	"       tablet cell:\"zone1\" uid:100 ",
	"Deleting vreplication streams on:",
	"       Keyspace customer, Shard -80, Tablet 200, Workflow p2c, DbName vt_customer",
	"       Keyspace customer, Shard 80-, Tablet 300, Workflow p2c, DbName vt_customer",
	"Unlock keyspace customer",
	"Unlock keyspace product",
}

var dryRunResultsReadCustomerShard = []string{
	"Lock keyspace product",
	"Switch reads for tables customer to keyspace customer",
	"Unlock keyspace product",
}

var dryrunresultsswitchwritesM2m3 = []string{
	"Lock keyspace merchant",
	"Stop streams on keyspace merchant",
	"/      Id 2 Keyspace customer Shard -80 Rules rules:<match:\"morders\" filter:\"select * from orders where in_keyrange(mname, 'merchant.md5', '-80')\" > at Position ",
	"/      Id 2 Keyspace customer Shard -80 Rules rules:<match:\"morders\" filter:\"select * from orders where in_keyrange(mname, 'merchant.md5', '80-')\" > at Position ",
	"/      Id 3 Keyspace customer Shard 80- Rules rules:<match:\"morders\" filter:\"select * from orders where in_keyrange(mname, 'merchant.md5', '-80')\" > at Position ",
	"/      Id 3 Keyspace customer Shard 80- Rules rules:<match:\"morders\" filter:\"select * from orders where in_keyrange(mname, 'merchant.md5', '80-')\" > at Position ",
	"/      Id 4 Keyspace customer Shard -80 Rules rules:<match:\"msales\" filter:\"select mname, count(*) as kount, sum(price) as amount from orders where in_keyrange(mname, 'merchant.md5', '-80') group by mname\" > at Position ",
	"/      Id 4 Keyspace customer Shard -80 Rules rules:<match:\"msales\" filter:\"select mname, count(*) as kount, sum(price) as amount from orders where in_keyrange(mname, 'merchant.md5', '80-') group by mname\" > at Position ",
	"/      Id 5 Keyspace customer Shard 80- Rules rules:<match:\"msales\" filter:\"select mname, count(*) as kount, sum(price) as amount from orders where in_keyrange(mname, 'merchant.md5', '-80') group by mname\" > at Position ",
	"/      Id 5 Keyspace customer Shard 80- Rules rules:<match:\"msales\" filter:\"select mname, count(*) as kount, sum(price) as amount from orders where in_keyrange(mname, 'merchant.md5', '80-') group by mname\" > at Position ",
	"Stop writes on keyspace merchant, tables /.*:",
	"       Keyspace merchant, Shard -80 at Position ",
	"       Keyspace merchant, Shard 80- at Position ",
	"Wait for VReplication on stopped streams to catchup for upto 30s",
	"Create reverse replication workflow m2m3_reverse",
	"Create journal entries on source databases",
	"Enable writes on keyspace merchant tables /.*",
	"Switch routing from keyspace merchant to keyspace merchant",
	"IsMasterServing will be set to false for:",
	"       Shard -80, Tablet cell:\"zone1\" uid:400 ",
	"       Shard 80-, Tablet cell:\"zone1\" uid:500 ",
	"IsMasterServing will be set to true for:",
	"       Shard -40, Tablet cell:\"zone1\" uid:1600 ",
	"       Shard 40-c0, Tablet cell:\"zone1\" uid:1700 ",
	"       Shard c0-, Tablet cell:\"zone1\" uid:1800 ",
	"SwitchWrites completed, freeze and delete vreplication streams on:",
	"       tablet cell:\"zone1\" uid:1600 ",
	"       tablet cell:\"zone1\" uid:1700 ",
	"       tablet cell:\"zone1\" uid:1800 ",
	"Start reverse replication streams on:",
	"       tablet cell:\"zone1\" uid:400 ",
	"       tablet cell:\"zone1\" uid:500 ",
	"Deleting vreplication streams on:",
	"       Keyspace merchant, Shard -40, Tablet 1600, Workflow m2m3, DbName vt_merchant",
	"       Keyspace merchant, Shard 40-c0, Tablet 1700, Workflow m2m3, DbName vt_merchant",
	"       Keyspace merchant, Shard c0-, Tablet 1800, Workflow m2m3, DbName vt_merchant",
	"Unlock keyspace merchant",
}
