{
 "kind": "discovery#restDescription",
 "etag": "\"C5oy1hgQsABtYOYIOXWcR3BgYqU/mk_oLjlaBwJ1BcBJ5yykCFb6u3w\"",
 "discoveryVersion": "v1",
 "id": "classroom:v1",
 "name": "classroom",
 "version": "v1",
 "revision": "20161006",
 "title": "Google Classroom API",
 "description": "Manages classes, rosters, and invitations in Google Classroom.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/classroom/",
 "protocol": "rest",
 "baseUrl": "https://classroom.googleapis.com/",
 "basePath": "",
 "rootUrl": "https://classroom.googleapis.com/",
 "servicePath": "",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/classroom.course-work.readonly": {
     "description": "View instructions for teacher-assigned work in your Google Classroom classes"
    },
    "https://www.googleapis.com/auth/classroom.courses": {
     "description": "Manage your Google Classroom classes"
    },
    "https://www.googleapis.com/auth/classroom.courses.readonly": {
     "description": "View your Google Classroom classes"
    },
    "https://www.googleapis.com/auth/classroom.coursework.me": {
     "description": "Manage your course work and view your grades in Google Classroom"
    },
    "https://www.googleapis.com/auth/classroom.coursework.me.readonly": {
     "description": "View your course work and grades in Google Classroom"
    },
    "https://www.googleapis.com/auth/classroom.coursework.students": {
     "description": "Manage course work and grades for students in the Google Classroom classes you teach and view the course work and grades for classes you administer"
    },
    "https://www.googleapis.com/auth/classroom.coursework.students.readonly": {
     "description": "View course work and grades for students in the Google Classroom classes you teach or administer"
    },
    "https://www.googleapis.com/auth/classroom.profile.emails": {
     "description": "View the email addresses of people in your classes"
    },
    "https://www.googleapis.com/auth/classroom.profile.photos": {
     "description": "View the profile photos of people in your classes"
    },
    "https://www.googleapis.com/auth/classroom.rosters": {
     "description": "Manage your Google Classroom class rosters"
    },
    "https://www.googleapis.com/auth/classroom.rosters.readonly": {
     "description": "View your Google Classroom class rosters"
    },
    "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly": {
     "description": "View your course work and grades in Google Classroom"
    },
    "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly": {
     "description": "View course work and grades for students in the Google Classroom classes you teach or administer"
    }
   }
  }
 },
 "resources": {
  "courses": {
   "methods": {
    "create": {
     "id": "classroom.courses.create",
     "path": "v1/courses",
     "httpMethod": "POST",
     "description": "Creates a course. The user specified in `ownerId` is the owner of the created course and added as a teacher. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses or for access errors. * `NOT_FOUND` if the primary teacher is not a valid user. * `FAILED_PRECONDITION` if the course owner's account is disabled or for the following request errors: * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if an [...]",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "get": {
     "id": "classroom.courses.get",
     "path": "v1/courses/{id}",
     "httpMethod": "GET",
     "description": "Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses",
      "https://www.googleapis.com/auth/classroom.courses.readonly"
     ]
    },
    "update": {
     "id": "classroom.courses.update",
     "path": "v1/courses/{id}",
     "httpMethod": "PUT",
     "description": "Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "patch": {
     "id": "classroom.courses.patch",
     "path": "v1/courses/{id}",
     "httpMethod": "PATCH",
     "description": "Updates one or more fields in a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "delete": {
     "id": "classroom.courses.delete",
     "path": "v1/courses/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses"
     ]
    },
    "list": {
     "id": "classroom.courses.list",
     "path": "v1/courses",
     "httpMethod": "GET",
     "description": "Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.courses",
      "https://www.googleapis.com/auth/classroom.courses.readonly"
     ]
    }
   },
   "resources": {
    "aliases": {
     "methods": {
      "create": {
       "id": "classroom.courses.aliases.create",
       "path": "v1/courses/{courseId}/aliases",
       "httpMethod": "POST",
       "description": "Creates an alias for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the alias or for access errors. * `NOT_FOUND` if the course does not exist. * `ALREADY_EXISTS` if the alias already exists.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.courses"
       ]
      },
      "delete": {
       "id": "classroom.courses.aliases.delete",
       "path": "v1/courses/{courseId}/aliases/{alias}",
       "httpMethod": "DELETE",
       "description": "Deletes an alias of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to remove the alias or for access errors. * `NOT_FOUND` if the alias does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.courses"
       ]
      },
      "list": {
       "id": "classroom.courses.aliases.list",
       "path": "v1/courses/{courseId}/aliases",
       "httpMethod": "GET",
       "description": "Returns a list of aliases for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the course or for access errors. * `NOT_FOUND` if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.courses",
        "https://www.googleapis.com/auth/classroom.courses.readonly"
       ]
      }
     }
    },
    "teachers": {
     "methods": {
      "create": {
       "id": "classroom.courses.teachers.create",
       "path": "v1/courses/{courseId}/teachers",
       "httpMethod": "POST",
       "description": "Creates a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create teachers in this course or for access errors. * `NOT_FOUND` if the requested course ID does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled, for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReached * UserGroupsMembershipLimitReached * `ALREAD[...]",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "get": {
       "id": "classroom.courses.teachers.get",
       "path": "v1/courses/{courseId}/teachers/{userId}",
       "httpMethod": "GET",
       "description": "Returns a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      },
      "delete": {
       "id": "classroom.courses.teachers.delete",
       "path": "v1/courses/{courseId}/teachers/{userId}",
       "httpMethod": "DELETE",
       "description": "Deletes a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of this course.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "list": {
       "id": "classroom.courses.teachers.list",
       "path": "v1/courses/{courseId}/teachers",
       "httpMethod": "GET",
       "description": "Returns a list of teachers of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      }
     }
    },
    "students": {
     "methods": {
      "create": {
       "id": "classroom.courses.students.create",
       "path": "v1/courses/{courseId}/students",
       "httpMethod": "POST",
       "description": "Adds a user as a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create students in this course or for access errors. * `NOT_FOUND` if the requested course ID does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled, for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if the user[...]",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "get": {
       "id": "classroom.courses.students.get",
       "path": "v1/courses/{courseId}/students/{userId}",
       "httpMethod": "GET",
       "description": "Returns a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      },
      "delete": {
       "id": "classroom.courses.students.delete",
       "path": "v1/courses/{courseId}/students/{userId}",
       "httpMethod": "DELETE",
       "description": "Deletes a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.rosters"
       ]
      },
      "list": {
       "id": "classroom.courses.students.list",
       "path": "v1/courses/{courseId}/students",
       "httpMethod": "GET",
       "description": "Returns a list of students of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/classroom.profile.photos",
        "https://www.googleapis.com/auth/classroom.rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly"
       ]
      }
     }
    },
    "courseWork": {
     "methods": {
      "create": {
       "id": "classroom.courses.courseWork.create",
       "path": "v1/courses/{courseId}/courseWork",
       "httpMethod": "POST",
       "description": "Creates course work. The resulting course work (and corresponding student submissions) are associated with the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to make the request. Classroom API requests to modify course work and student submissions must be made with an OAuth client ID from the associated Developer Console project. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting [...]",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.coursework.students"
       ]
      },
      "get": {
       "id": "classroom.courses.courseWork.get",
       "path": "v1/courses/{courseId}/courseWork/{id}",
       "httpMethod": "GET",
       "description": "Returns course work. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or course work, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or course work does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.course-work.readonly",
        "https://www.googleapis.com/auth/classroom.coursework.me",
        "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
        "https://www.googleapis.com/auth/classroom.coursework.students",
        "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
       ]
      },
      "list": {
       "id": "classroom.courses.courseWork.list",
       "path": "v1/courses/{courseId}/courseWork",
       "httpMethod": "GET",
       "description": "Returns a list of course work that the requester is permitted to view. Course students may only view `PUBLISHED` course work. Course teachers and domain administrators may view all course work. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course does not exist.",
       "scopes": [
        "https://www.googleapis.com/auth/classroom.course-work.readonly",
        "https://www.googleapis.com/auth/classroom.coursework.me",
        "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
        "https://www.googleapis.com/auth/classroom.coursework.students",
        "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
       ]
      }
     },
     "resources": {
      "studentSubmissions": {
       "methods": {
        "get": {
         "id": "classroom.courses.courseWork.studentSubmissions.get",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
         "httpMethod": "GET",
         "description": "Returns a student submission. * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course, course work, or student submission or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course, course work, or student submission does not exist.",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.me",
          "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
          "https://www.googleapis.com/auth/classroom.coursework.students",
          "https://www.googleapis.com/auth/classroom.coursework.students.readonly",
          "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly",
          "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
         ]
        },
        "patch": {
         "id": "classroom.courses.courseWork.studentSubmissions.patch",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
         "httpMethod": "PATCH",
         "description": "Updates one or more fields of a student submission. See google.classroom.v1.StudentSubmission for details of which fields may be updated and who may change them. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corre[...]",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.me",
          "https://www.googleapis.com/auth/classroom.coursework.students"
         ]
        },
        "list": {
         "id": "classroom.courses.courseWork.studentSubmissions.list",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions",
         "httpMethod": "GET",
         "description": "Returns a list of student submissions that the requester is permitted to view, factoring in the OAuth scopes of the request. `-` may be specified as the `course_work_id` to include student submissions for multiple course work items. Course students may only view their own work. Course teachers and domain administrators may view all student submissions. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access t[...]",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.me",
          "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
          "https://www.googleapis.com/auth/classroom.coursework.students",
          "https://www.googleapis.com/auth/classroom.coursework.students.readonly",
          "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly",
          "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
         ]
        },
        "turnIn": {
         "id": "classroom.courses.courseWork.studentSubmissions.turnIn",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn",
         "httpMethod": "POST",
         "description": "Turns in a student submission. Turning in a student submission transfers ownership of attached Drive files to the teacher and may also update the submission state. This may only be called by the student that owns the specified student submission. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error code[...]",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.me"
         ]
        },
        "reclaim": {
         "id": "classroom.courses.courseWork.studentSubmissions.reclaim",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim",
         "httpMethod": "POST",
         "description": "Reclaims a student submission on behalf of the student that owns it. Reclaiming a student submission transfers ownership of attached Drive files to the student and update the submission state. Only the student that ownes the requested student submission may call this method, and only for a student submission that has been turned in. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to[...]",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.me"
         ]
        },
        "return": {
         "id": "classroom.courses.courseWork.studentSubmissions.return",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return",
         "httpMethod": "POST",
         "description": "Returns a student submission. Returning a student submission transfers ownership of attached Drive files to the student and may also update the submission state. Unlike the Classroom application, returning a student submission does not set assignedGrade to the draftGrade value. Only a teacher of the course that contains the requested student submission may call this method. This request must be made by the Developer Console project of the [OAuth client ID](https://suppor[...]",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.students"
         ]
        },
        "modifyAttachments": {
         "id": "classroom.courses.courseWork.studentSubmissions.modifyAttachments",
         "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments",
         "httpMethod": "POST",
         "description": "Modifies attachments of student submission. Attachments may only be added to student submissions whose type is `ASSIGNMENT`. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or course work, if the use[...]",
         "scopes": [
          "https://www.googleapis.com/auth/classroom.coursework.me",
          "https://www.googleapis.com/auth/classroom.coursework.students"
         ]
        }
       }
      }
     }
    }
   }
  },
  "userProfiles": {
   "methods": {
    "get": {
     "id": "classroom.userProfiles.get",
     "path": "v1/userProfiles/{userId}",
     "httpMethod": "GET",
     "description": "Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile or if no profile exists with the requested ID or for access errors.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.profile.emails",
      "https://www.googleapis.com/auth/classroom.profile.photos",
      "https://www.googleapis.com/auth/classroom.rosters",
      "https://www.googleapis.com/auth/classroom.rosters.readonly"
     ]
    }
   },
   "resources": {
    "guardianInvitations": {
     "methods": {
      "list": {
       "id": "classroom.userProfiles.guardianInvitations.list",
       "path": "v1/userProfiles/{studentId}/guardianInvitations",
       "httpMethod": "GET",
       "description": "Returns a list of guardian invitations that the requesting user is permitted to view, filtered by the parameters provided. This method returns the following error codes: * `PERMISSION_DENIED` if a `student_id` is specified, and the requesting user is not permitted to view guardian invitations for that student, if `\"-\"` is specified as the `student_id` and the user is not a domain administrator, if guardians are not enabled for the domain in question, or for other access [...]"
      },
      "get": {
       "id": "classroom.userProfiles.guardianInvitations.get",
       "path": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
       "httpMethod": "GET",
       "description": "Returns a specific guardian invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view guardian invitations for the student identified by the `student_id`, if guardians are not enabled for the domain in question, or for other access errors. * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot be recognized (it is not an email address, nor a `student_id` from the API, nor the literal[...]"
      },
      "create": {
       "id": "classroom.userProfiles.guardianInvitations.create",
       "path": "v1/userProfiles/{studentId}/guardianInvitations",
       "httpMethod": "POST",
       "description": "Creates a guardian invitation, and sends an email to the guardian asking them to confirm that they are the student's guardian. Once the guardian accepts the invitation, their `state` will change to `COMPLETED` and they will start receiving guardian notifications. A `Guardian` resource will also be created to represent the active guardian. The request object must have the `student_id` and `invited_email_address` fields set. Failing to set these fields, or setting any other [...]"
      },
      "patch": {
       "id": "classroom.userProfiles.guardianInvitations.patch",
       "path": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
       "httpMethod": "PATCH",
       "description": "Modifies a guardian invitation. Currently, the only valid modification is to change the `state` from `PENDING` to `COMPLETE`. This has the effect of withdrawing the invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the current user does not have permission to manage guardians, if guardians are not enabled for the domain in question or for other access errors. * `FAILED_PRECONDITION` if the guardian link is not in the `PENDING` state. * `IN[...]"
      }
     }
    },
    "guardians": {
     "methods": {
      "list": {
       "id": "classroom.userProfiles.guardians.list",
       "path": "v1/userProfiles/{studentId}/guardians",
       "httpMethod": "GET",
       "description": "Returns a list of guardians that the requesting user is permitted to view, restricted to those that match the request. To list guardians for any student that the requesting user may view guardians for, use the literal character `-` for the student ID. This method returns the following error codes: * `PERMISSION_DENIED` if a `student_id` is specified, and the requesting user is not permitted to view guardian information for that student, if `\"-\"` is specified as the `stud[...]"
      },
      "get": {
       "id": "classroom.userProfiles.guardians.get",
       "path": "v1/userProfiles/{studentId}/guardians/{guardianId}",
       "httpMethod": "GET",
       "description": "Returns a specific guardian. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view guardian information for the student identified by the `student_id`, if guardians are not enabled for the domain in question, or for other access errors. * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot be recognized (it is not an email address, nor a `student_id` from the API, nor the literal string `me[...]"
      },
      "delete": {
       "id": "classroom.userProfiles.guardians.delete",
       "path": "v1/userProfiles/{studentId}/guardians/{guardianId}",
       "httpMethod": "DELETE",
       "description": "Deletes a guardian. The guardian will no longer receive guardian notifications and the guardian will no longer be accessible via the API. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to manage guardians for the student identified by the `student_id`, if guardians are not enabled for the domain in question, or for other access errors. * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot be[...]"
      }
     }
    }
   }
  },
  "invitations": {
   "methods": {
    "create": {
     "id": "classroom.invitations.create",
     "path": "v1/invitations",
     "httpMethod": "POST",
     "description": "Creates an invitation. Only one invitation for a user and course may exist at a time. Delete and re-create an invitation to make changes. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create invitations for this course or for access errors. * `NOT_FOUND` if the course or the user does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled or if the user already has this role or a role w[...]",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters"
     ]
    },
    "get": {
     "id": "classroom.invitations.get",
     "path": "v1/invitations/{id}",
     "httpMethod": "GET",
     "description": "Returns an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters",
      "https://www.googleapis.com/auth/classroom.rosters.readonly"
     ]
    },
    "delete": {
     "id": "classroom.invitations.delete",
     "path": "v1/invitations/{id}",
     "httpMethod": "DELETE",
     "description": "Deletes an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters"
     ]
    },
    "list": {
     "id": "classroom.invitations.list",
     "path": "v1/invitations",
     "httpMethod": "GET",
     "description": "Returns a list of invitations that the requesting user is permitted to view, restricted to those that match the list request. *Note:* At least one of `user_id` or `course_id` must be supplied. Both fields can be supplied. This method returns the following error codes: * `PERMISSION_DENIED` for access errors.",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters",
      "https://www.googleapis.com/auth/classroom.rosters.readonly"
     ]
    },
    "accept": {
     "id": "classroom.invitations.accept",
     "path": "v1/invitations/{id}:accept",
     "httpMethod": "POST",
     "description": "Accepts an invitation, removing it and adding the invited user to the teachers or students (as appropriate) of the specified course. Only the invited user may accept an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to accept the requested invitation or for access errors. * `FAILED_PRECONDITION` for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReach[...]",
     "scopes": [
      "https://www.googleapis.com/auth/classroom.rosters"
     ]
    }
   }
  }
 }
}
