// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	rest "k8s.io/client-go/rest"

	v1beta1 "vitess.io/vitess/go/vt/topo/k8stopo/apis/topo/v1beta1"
	"vitess.io/vitess/go/vt/topo/k8stopo/client/clientset/versioned/scheme"
)

type TopoV1beta1Interface interface {
	RESTClient() rest.Interface
	VitessTopoNodesGetter
}

// TopoV1beta1Client is used to interact with features provided by the topo.vitess.io group.
type TopoV1beta1Client struct {
	restClient rest.Interface
}

func (c *TopoV1beta1Client) VitessTopoNodes(namespace string) VitessTopoNodeInterface {
	return newVitessTopoNodes(c, namespace)
}

// NewForConfig creates a new TopoV1beta1Client for the given config.
func NewForConfig(c *rest.Config) (*TopoV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &TopoV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new TopoV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *TopoV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new TopoV1beta1Client for the given RESTClient.
func New(c rest.Interface) *TopoV1beta1Client {
	return &TopoV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *TopoV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
