ARG GIT_COMMIT

FROM square-vitess-build-${GIT_COMMIT} as build

FROM debian:stretch-slim

# Setup the Vitess environment
ENV VTTOP /vt/src/vitess.io/vitess
ENV VTROOT /vt
ENV GOTOP $VTTOP/go
ENV VTDATAROOT $VTROOT/vtdataroot
ENV GOBIN $VTROOT/bin
ENV GOPATH $VTROOT
ENV PATH $VTROOT/bin:$PATH
ENV VT_MYSQL_ROOT /usr
ENV PKG_CONFIG_PATH $VTROOT/lib

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gnupg dirmngr ca-certificates software-properties-common && \
  for i in $(seq 1 10); do apt-key adv --no-tty --recv-keys --keyserver keyserver.ubuntu.com 5072E1F5 && break; done && \
  add-apt-repository 'deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7' && \
  for i in $(seq 1 10); do apt-key adv --no-tty --keyserver keyserver.ubuntu.com --recv-keys 9334A25F8507EFA5 && break; done && \
  echo 'deb http://repo.percona.com/apt stretch main' > /etc/apt/sources.list.d/percona.list && \
  { \
      echo debconf debconf/frontend select Noninteractive; \
      echo percona-server-server-5.7 percona-server-server/root_password password 'unused'; \
      echo percona-server-server-5.7 percona-server-server/root_password_again password 'unused'; \
  } | debconf-set-selections && \
  apt-get update -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server libmysqlclient-dev libdbd-mysql-perl rsync libev4 percona-xtrabackup-24 && \
  rm -rf /var/lib/apt/lists/* \
  && groupadd -r vitess && useradd -r -g vitess vitess \
  && mkdir -p /vt && chown -R vitess:vitess /vt

USER vitess

# Make directories and copy binaries over from the vitess build image
RUN mkdir -p /vt/src/vitess.io/vitess/web/vtctld2 && mkdir -p /vt/vtdataroot/ && mkdir -p /vt/bin
COPY --from=build /vt/src/vitess.io/vitess/config /vt/config
COPY --from=build /vt/src/vitess.io/vitess/config /vt/src/vitess.io/vitess/config
COPY --from=build /vt/src/vitess.io/vitess/web/vtctld2/app /vt/src/vitess.io/web/vtctld2/
COPY --from=build /vt/bin/mysqlctl /vt/bin/mysqlctld /vt/bin/vtcombo /vt/bin/vttestserver /vt/bin/
