SET profiling=1;
SELECT TABLE_NAME as table_name, COLUMN_NAME as column_name FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND LOWER(INDEX_NAME) = 'primary' ORDER BY table_name, SEQ_IN_INDEX;
SELECT TABLE_NAME as table_name, COLUMN_NAME as column_name FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND LOWER(INDEX_NAME) = 'primary' ORDER BY table_name, SEQ_IN_INDEX;
SELECT TABLE_NAME as table_name, COLUMN_NAME as column_name FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME='t1250' AND LOWER(INDEX_NAME) = 'primary' ORDER BY SEQ_IN_INDEX;
SHOW PROFILES;
