#!/bin/bash

function _print_download()
{
  echo "To make this script work, you need to download upload.py from:"
  echo "http://code.google.com/p/rietveld/wiki/UploadPyUsage"
  echo "Copy the file to your path, and chmod to make it executable."
  exit 1
}

function parse_git_branch {
  branch=$(git branch --no-color 2> /dev/null |grep '*'|awk '{print $2}')
  if [ ! -z $branch ]; then
    echo " $branch"
  else
    echo "could not identify current branch"
    exit 1
  fi
}

if [ "$(which upload.py)" == "" ]; then
  _print_download
fi

echo "Visit https://accounts.google.com/b/0/IssuedAuthSubTokens to generate an app specific password."
upload.py --rev master -y -s codereview.appspot.com -e ${USER}@google.com -cc yt-vt-issues@google.com --send_mail $*
