CREATE TABLE IF NOT EXISTS _vt.views
(
    TABLE_NAME varchar(64) NOT NULL,
    VIEW_DEFINITION longtext NOT NULL,
    CREATE_STATEMENT longtext NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TABLE_NAME)
) engine = InnoDB
