name: Assign Milestone

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Assign Milestone
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # We must explicitly checkout the base's SHA to avoid executing any code coming from
          # the PR's SHA - Which would be executed in the base branch's context.
          # This is really important to limit any sort of pwn requests.
          ref: ${{ github.base_ref }}
          persist-credentials: 'false'

      - name: Assign Milestone
        run: |
          # Ensure the content we sed from version.go is sanitized and match the correct format
          VERSION=$(sed -n 's/.*versionName.*\"\([[:digit:]\.]*\).*\"/\1/p' ./go/vt/servenv/version.go)
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $VERSION"
            exit 1
          fi

          gh pr edit ${{ github.event.number }} --milestone "v$VERSION"
