name: check_make_vtadmin_authz_testgen
on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
    tags: '**'
  pull_request:
    branches: '**'

permissions: read-all

jobs:
  build:
    name: Check Make vtadmin_authz_testgen
    runs-on: ubuntu-24.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Skip CI
      run: |
        if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
          echo "skipping CI due to the 'Skip CI' label"
          exit 1
        fi

    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: 'false'

    - name: Check for changes in relevant files
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
      id: changes
      with:
        token: ''
        filters: |
          vtadmin_changes:
            - 'bootstrap.sh'
            - 'tools/**'
            - 'build.env'
            - 'go.sum'
            - 'go.mod'
            - 'Makefile'
            - 'go/vt/vtadmin/**'
            - '.github/workflows/check_make_vtadmin_authz_testgen.yml'

    - name: Tune the OS
      if: steps.changes.outputs.vtadmin_changes == 'true'
      timeout-minutes: 5
      uses: ./.github/actions/tune-os

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      if: steps.changes.outputs.vtadmin_changes == 'true'
      with:
        go-version-file: go.mod
        cache: ${{ (github.base_ref == 'main' || (github.base_ref == '' && github.ref_name == 'main')) && 'true' || 'false' }}
        cache-dependency-path: |
          go.sum
          tools/**/go.sum

    - name: Get dependencies
      if: steps.changes.outputs.vtadmin_changes == 'true'
      timeout-minutes: 5
      run: |
        sudo apt-get update
        sudo apt-get install -y make unzip g++ etcd-client etcd-server curl git wget
        sudo service etcd stop
        go mod download

    - name: Run make minimaltools
      if: steps.changes.outputs.vtadmin_changes == 'true'
      timeout-minutes: 5
      run: |
        make minimaltools

    - name: check_make_vtadmin_authz_testgen
      if: steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        tools/check_make_vtadmin_authz_testgen.sh
