name: e2e_race
on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
    tags: '**'
  pull_request:
    branches: '**'
permissions: read-all
jobs:

  build:
    name: End-to-End Test (Race)
    runs-on: ubuntu-24.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Skip CI
      run: |
        if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
          echo "skipping CI due to the 'Skip CI' label"
          exit 1
        fi

    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: 'false'

    - name: Check for changes in relevant files
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: changes
      with:
        token: ''
        filters: |
          end_to_end:
            - 'go/**/*.go'
            - 'test.go'
            - 'Makefile'
            - 'build.env'
            - 'go.sum'
            - 'go.mod'
            - 'proto/*.proto'
            - 'tools/**'
            - 'config/**'
            - 'bootstrap.sh'
            - '.github/workflows/e2e_race.yml'

    - name: Set up Go
      if: steps.changes.outputs.end_to_end == 'true'
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: ${{ (github.base_ref == 'main' || (github.base_ref == '' && github.ref_name == 'main')) && 'true' || 'false' }}

    - name: Tune the OS
      if: steps.changes.outputs.end_to_end == 'true'
      uses: ./.github/actions/tune-os

    - name: Setup MySQL
      if: steps.changes.outputs.end_to_end == 'true'
      uses: ./.github/actions/setup-mysql
      with:
        flavor: mysql-8.4

    - name: Get dependencies
      if: steps.changes.outputs.end_to_end == 'true'
      run: |
        sudo apt-get update
        
        # Install everything else we need, and configure
        sudo apt-get install -y make unzip g++ etcd-client etcd-server curl git wget xz-utils
        
        sudo service etcd stop

        go mod download

    - name: Run make minimaltools
      if: steps.changes.outputs.end_to_end == 'true'
      run: |
        make minimaltools

    - name: e2e_race
      if: steps.changes.outputs.end_to_end == 'true'
      timeout-minutes: 30
      run: |
        NOVTADMINBUILD=1 make e2e_test_race
