name: local_example
on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
    tags: '**'
  pull_request:
    branches: '**'
permissions: read-all

env:
  BOOTSTRAP_VERSION: "ci"
  BOOTSTRAP_FLAVOR: "mysql84"

jobs:

  build:
    name: Local example using ${{ matrix.topo }} on Ubuntu
    runs-on: ${{ github.repository == 'vitessio/vitess' && 'oracle-vm-16cpu-64gb-x86-64' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        topo: [etcd, zk2]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Skip CI
      run: |
        if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
          echo "skipping CI due to the 'Skip CI' label"
          exit 1
        fi

    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: 'false'

    - name: Check for changes in relevant files
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
      id: changes
      with:
        token: ''
        filters: |
          examples:
            - 'test/config.json'
            - 'go/**/!(*_test).go'
            - 'go/**/*.s'
            - 'go/vt/sidecardb/**/*.sql'
            - 'go/mysql/collations/colldata/**'
            - 'go/mysql/icuregex/internal/icudata/**'
            - 'test.go'
            - 'Makefile'
            - 'build.env'
            - 'go.sum'
            - 'go.mod'
            - 'proto/*.proto'
            - 'tools/**'
            - 'config/**'
            - 'bootstrap.sh'
            - 'examples/**'
            - '.github/workflows/local_example.yml'

    - name: Build bootstrap images
      if: steps.changes.outputs.examples == 'true'
      timeout-minutes: 15
      uses: ./.github/actions/build-bootstrap

    - name: Set up Go
      if: steps.changes.outputs.examples == 'true'
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
        cache: ${{ (github.base_ref == 'main' || (github.base_ref == '' && github.ref_name == 'main')) && 'true' || 'false' }}

    - name: Tune the OS
      if: steps.changes.outputs.examples == 'true'
      timeout-minutes: 5
      uses: ./.github/actions/tune-os

    - name: Get dependencies
      if: steps.changes.outputs.examples == 'true'
      timeout-minutes: 5
      run: |
        go mod download

    - name: Run make minimaltools
      if: steps.changes.outputs.examples == 'true'
      timeout-minutes: 5
      run: |
        make minimaltools

    - name: Build
      if: steps.changes.outputs.examples == 'true'
      timeout-minutes: 10
      run: |
        make build

    - name: local_example
      if: steps.changes.outputs.examples == 'true'
      timeout-minutes: 30
      run: |
        export TOPO=${{matrix.topo}}
        if [ "${{matrix.os}}" = "macos-latest" ]; then
          export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
        fi
        go run test.go -print-log -follow -pull=false -flavor=${{ env.BOOTSTRAP_FLAVOR }} -bootstrap-version=${{ env.BOOTSTRAP_VERSION }} local_example
